/**
 * Cambridge International AS & A Level -- Global Perspectives & Research 9239
 * (the AICE Diploma core, syllabus 2026-2028), English Language 9093 (Group 2,
 * syllabus 2027-2028) and Economics 9708 (Group 3, syllabus 2026-2028).
 *
 * Structure (components, minutes, marks, weights, routes) comes from the
 * sourced syllabi (builder.ts). Response formats follow the real papers:
 * source-based written responses, coursework essay, individual presentation +
 * reflective paper, research report + log, directed / comparative writing,
 * text and language-data analysis, essays, data response and multiple choice.
 * Interpretive work is scored against StudyUS practice rubrics by two
 * independent assessors (adjudication above the disagreement threshold;
 * REVIEW_REQUIRED at low confidence; audio / video always to human review).
 * All stimuli and items are ORIGINAL StudyUS practice.
 */
import { mc, rubricItem, portfolioItem, levels } from '../builders';
import { aiceConfig, type AiceItem, type AiceObjective } from './builder';

const en = 'en';
const NOTE = 'StudyUS practice rubric (Cambridge mark schemes and level descriptors are not reproduced). Totals match the official marks.';
type Crit = [id: string, name: string, max: number, d: [string, string, string, string]];
const rubric = (kind: 'ANALYTIC' | 'BEST_FIT', criteria: Crit[], threshold = 3) => ({
  kind,
  guidance: NOTE,
  disagreementThreshold: threshold,
  minConfidence: 0.6,
  criteria: criteria.map(([id, name, max, d]) => ({ id, name, maxMarks: max, descriptors: levels(max, d) })),
});
const T = (topic: string, ao: string) => ({ contentCategory: topic, assessmentObjective: ao, cognitiveDemand: 'EVALUATION' as const });

// ================================================================ 9239 GP&R
const PACKAGING = {
  key: 'aice.9239.packaging',
  title: 'Two sources on banning single-use plastic packaging',
  text:
    'Source A — from a blog by a city councillor (StudyUS practice source):\n"Our city sends 9,000 tonnes of plastic packaging to landfill every year. When the neighbouring town banned single-use packaging in shops, litter on its beaches fell by a third within two years, according to its own council survey. A ban is the fastest, fairest way to change habits: everyone follows the same rule."\n\n' +
    'Source B — from a letter by a small grocery owner to a local newspaper (StudyUS practice source):\n"Paper and glass alternatives cost me up to four times more and spoil faster. Large supermarkets can absorb the cost; corner shops like mine cannot. The town next door is often quoted, but its survey counted litter only on two beaches in summer. Education and deposit schemes would cut waste without closing small businesses."',
};
const GPR_OBJ: Record<string, AiceObjective[]> = {
  c1: [
    { code: 'aice.9239.c1.analysis', description: 'Written exam · Q1 structured short answers: identify and analyse arguments, evidence and perspectives in a source.', count: 1 },
    { code: 'aice.9239.c1.evaluation', description: 'Written exam · Q2 evaluate the reasoning and evidence of one source.', count: 1 },
    { code: 'aice.9239.c1.comparison', description: 'Written exam · Q3 compare and evaluate both sources and reach a supported judgement.', count: 1 },
  ],
  c2: [{ code: 'aice.9239.c2.essay', description: 'Essay · research a global issue from different perspectives and write a supported argument (1750–2000 words).', count: 1 }],
  c3: [{ code: 'aice.9239.c3.team-project', description: 'Team project · individual presentation of a solution to a local problem with global relevance + reflective paper.', count: 1 }],
  c4: [{ code: 'aice.9239.c4.research-report', description: 'Research report · independent research on a single question (up to 5000 words) + research log.', count: 1 }],
};
const GPR_ITEMS: AiceItem[] = [
  { objectiveCode: 'aice.9239.c1.analysis', content: rubricItem({ key: 'c1.q1', language: en, stimulus: PACKAGING, tags: T('Analysis of sources', 'AO1'), commandTerm: 'identify', question: '(a) Identify the main conclusion of Source A. (b) Explain one piece of evidence the author of Source B uses to challenge Source A.', explanation: 'A concludes that a ban is the fastest, fairest way to change habits; B challenges the beach-litter evidence (two beaches, summer only).', rubric: rubric('ANALYTIC', [['A', 'Main conclusion identified accurately', 2, ['Partly identified.', 'Identified but paraphrased loosely.', 'Identified accurately.', 'Identified accurately and concisely.']], ['B', 'Counter-evidence explained', 3, ['Evidence named only.', 'Evidence named with little explanation.', 'Evidence explained.', 'Evidence clearly explained in relation to Source A.']]], 1), modelAnswerSummary: 'Conclusion: a ban is the fastest and fairest way to change habits. Evidence: B says the neighbouring survey covered only two beaches in summer, so the one-third fall may not be representative.' }) },
  { objectiveCode: 'aice.9239.c1.evaluation', content: rubricItem({ key: 'c1.q2', language: en, stimulus: PACKAGING, tags: T('Evaluation of reasoning and evidence', 'AO1'), commandTerm: 'evaluate', question: 'Evaluate the strength of the reasoning and evidence in Source B.', explanation: 'Strengths: first-hand cost experience, identifies a limitation of the survey. Weaknesses: anecdotal costs, vested interest, alternatives asserted without evidence.', rubric: rubric('BEST_FIT', [['E', 'Evaluation of evidence (quality, relevance, sufficiency)', 7, ['Description of the source.', 'Some evaluative comments.', 'Clear evaluation of several aspects.', 'Sustained, balanced evaluation of evidence.']], ['R', 'Evaluation of reasoning and the author’s perspective / vested interest', 6, ['Little on reasoning.', 'Some reasoning issues noted.', 'Reasoning and perspective evaluated.', 'Perceptive evaluation of reasoning and perspective.']], ['J', 'Supported overall judgement', 2, ['No judgement.', 'Judgement asserted.', 'Judgement with some support.', 'Clear, well-supported judgement.']]]), modelAnswerSummary: 'B is credible on business costs (first-hand) and rightly questions the survey sample, but has a vested interest, gives no figures for spoilage, and asserts that education and deposits work without evidence; moderately strong overall.' }) },
  { objectiveCode: 'aice.9239.c1.comparison', content: rubricItem({ key: 'c1.q3', language: en, stimulus: PACKAGING, tags: T('Comparison of perspectives', 'AO1'), commandTerm: 'evaluate', question: 'Which source presents the more convincing argument about banning single-use plastic packaging? Refer to both sources and reach a supported judgement.', explanation: 'A balanced comparison of the reasoning, evidence and perspectives of both sources, with a justified judgement.', rubric: rubric('BEST_FIT', [['C', 'Comparison of the reasoning and evidence of both sources', 12, ['One source only.', 'Some comparison, mostly descriptive.', 'Clear comparison of reasoning and evidence.', 'Sustained, insightful comparison.']], ['P', 'Perspectives and context (who argues, why, from where)', 7, ['Little on perspectives.', 'Perspectives named.', 'Perspectives explained.', 'Perspectives evaluated in context.']], ['J', 'Reasoned, supported judgement', 6, ['No judgement.', 'Judgement asserted.', 'Judgement supported in part.', 'Convincing, well-supported judgement.']]], 4), modelAnswerSummary: 'A has a clear rule-based argument but relies on a weak survey; B identifies that weakness and real costs but has a vested interest and unsupported alternatives. A reasoned judgement either way, weighing evidence quality and perspectives.' }) },
  { objectiveCode: 'aice.9239.c2.essay', content: portfolioItem({ key: 'c2.essay', language: en, tags: T('Research essay', 'AO1'), commandTerm: 'research', question: 'Practice essay — devise one question about a global issue (e.g. "Should countries pay to protect rainforests outside their borders?"). Research different perspectives and write an essay of 1750–2000 words with a supported conclusion. Upload the essay (PDF or document) and a list of your sources.', explanation: 'Assessed against a StudyUS practice rubric.', portfolio: { componentKind: 'OTHER', statementRequired: false, requiredArtifacts: [{ kind: 'PDF', min: 1, max: 1, label: 'Essay (1750–2000 words)' }, { kind: 'BIBLIOGRAPHY', min: 1, max: 1, label: 'List of sources' }], rubric: rubric('BEST_FIT', [['Q', 'A focused question that allows different perspectives', 6, ['Unfocused.', 'Broad but workable.', 'Focused and debatable.', 'Sharply focused, genuinely debatable.']], ['R', 'Research and use of evidence from different perspectives', 14, ['Little research.', 'Some relevant evidence.', 'Relevant, varied evidence from different perspectives.', 'Wide, well-selected evidence across perspectives.']], ['E', 'Evaluation of arguments and evidence; supported conclusion', 14, ['Descriptive.', 'Some evaluation.', 'Clear evaluation and a supported conclusion.', 'Sustained evaluation and a convincing conclusion.']], ['C', 'Communication: structure, clarity, referencing', 6, ['Hard to follow.', 'Mostly clear.', 'Clear structure and referencing.', 'Fluent, well structured, fully referenced.']]], 5) } }) },
  { objectiveCode: 'aice.9239.c3.team-project', content: portfolioItem({ key: 'c3.project', language: en, tags: T('Team project', 'AO3'), commandTerm: 'present', question: 'Practice team project — with your team, choose a local problem with global relevance (e.g. food waste in your school). Prepare YOUR individual presentation (max 10 minutes) of one perspective and a proposed solution, then write a reflective paper (max 800 words) on how working in a team affected your learning. Upload your slides, a recording or verbatim transcript, and the reflective paper.', explanation: 'Assessed against a StudyUS practice rubric; recordings always go to human review.', portfolio: { componentKind: 'PROJECT', statementRequired: false, requiredArtifacts: [{ kind: 'PRESENTATION', min: 1, max: 1, label: 'Presentation slides (PDF)' }, { kind: 'VIDEO', min: 0, max: 1, label: 'Recording of the presentation (optional — human review)' }, { kind: 'TEXT', min: 1, max: 2, label: 'Verbatim transcript and reflective paper (max 800 words)' }], rubric: rubric('BEST_FIT', [['P', 'Presentation: problem, perspective and evidence', 12, ['Unclear problem.', 'Problem stated with some evidence.', 'Clear problem, perspective and evidence.', 'Compelling problem framing with strong evidence.']], ['S', 'Proposed solution and its evaluation', 10, ['No real solution.', 'A solution with little evaluation.', 'A reasoned solution with evaluation.', 'A well-evaluated, feasible solution.']], ['D', 'Delivery and communication for the audience', 8, ['Hard to follow.', 'Mostly clear.', 'Clear and engaging.', 'Highly effective for the audience.']], ['F', 'Reflective paper: teamwork and learning', 10, ['Description only.', 'Some reflection.', 'Clear reflection on collaboration and learning.', 'Insightful, critical reflection.']]], 5) } }) },
  { objectiveCode: 'aice.9239.c4.research-report', content: portfolioItem({ key: 'c4.report', language: en, tags: T('Research report', 'AO1'), commandTerm: 'research', question: 'Practice research report — design one research question for a non-specialist audience, carry out independent research, and write a report of up to 5000 words. Upload the report and your research log.', explanation: 'Assessed against a StudyUS practice rubric.', portfolio: { componentKind: 'OTHER', statementRequired: false, requiredArtifacts: [{ kind: 'PDF', min: 1, max: 1, label: 'Research report (up to 5000 words)' }, { kind: 'PROCESS_EVIDENCE', min: 1, max: 3, label: 'Research log' }], rubric: rubric('BEST_FIT', [['Q', 'Research question and design', 15, ['Unclear question.', 'A workable question.', 'A focused question with a suitable design.', 'A sharp question with a well-justified design.']], ['M', 'Research methods and use of sources', 20, ['Little research.', 'Some suitable research.', 'Appropriate methods and sources.', 'Rigorous methods and well-evaluated sources.']], ['A', 'Analysis, evaluation and conclusions', 30, ['Descriptive.', 'Some analysis.', 'Clear analysis and supported conclusions.', 'Sophisticated analysis and convincing conclusions.']], ['C', 'Communication for a non-specialist audience', 10, ['Hard to follow.', 'Mostly clear.', 'Clear and well structured.', 'Fluent and accessible throughout.']], ['L', 'Research log: reflection on the process', 10, ['Minimal log.', 'Some record of the process.', 'A clear, reflective log.', 'A detailed, critically reflective log.']]], 8) } }) },
];

// ================================================================ 9093 English Language
const TRAVEL = { key: 'aice.9093.travel', title: 'Text 1 — a travel blog (StudyUS practice text)', text: 'By the third day in the valley I had stopped checking my phone. The village had one café, one bus and, as far as I could tell, one opinion about strangers: welcome them, feed them, then ask them questions until sunset. Mornings smelled of woodsmoke and coffee strong enough to stand a spoon in. I walked the terraces with Ana, who has farmed them for forty years and who laughed when I asked whether she ever took holidays. "Why would I leave," she said, "when the world keeps coming here?"' };
const SPEECH = { key: 'aice.9093.speech', title: 'Text 2 — a school speech day address (StudyUS practice text)', text: 'Graduates, you were told that the future belongs to you. I would like to correct that: the future does not belong to anyone. It is borrowed — from the people who will live in it after us. So borrow it carefully. Ask the awkward question. Fix the thing nobody else wants to fix. And when you succeed, as many of you will, remember the people who held the ladder.' };
const NGRAM = { key: 'aice.9093.ngram', title: 'Data — frequency of "awesome" per million words in a corpus (StudyUS practice data)', text: '1900: 0.6 · 1950: 0.9 · 1980: 2.1 · 2000: 6.4 · 2019: 11.8\nMost frequent collocates in 1950: awesome power, awesome responsibility. In 2019: awesome job, totally awesome.' };
const TRANSCRIPT = { key: 'aice.9093.transcript', title: 'Transcript — a child (2 years 6 months) and parent (StudyUS practice data)', text: 'Child: daddy goed work\nParent: Daddy went to work, yes. Where did he go?\nChild: in car. big car\nParent: In the big car. What colour is it?\nChild: is blue. I want go too\nParent: You want to go too? Tomorrow, maybe.' };
const ENG_OBJ: Record<string, AiceObjective[]> = {
  p1: [
    { code: 'aice.9093.p1.directed', description: 'Reading · Section A: directed response writing and comparative analysis.', count: 1 },
    { code: 'aice.9093.p1.analysis', description: 'Reading · Section B: text analysis of form, structure and language.', count: 1 },
  ],
  p2: [
    { code: 'aice.9093.p2.shorter', description: 'Writing · Section A: shorter writing task and reflective commentary.', count: 1 },
    { code: 'aice.9093.p2.extended', description: 'Writing · Section B: extended writing (imaginative, discursive or critical).', count: 1 },
  ],
  p3: [
    { code: 'aice.9093.p3.change', description: 'Language analysis · Section A: language change (texts and corpus data).', count: 1 },
    { code: 'aice.9093.p3.acquisition', description: 'Language analysis · Section B: child language acquisition (transcript).', count: 1 },
  ],
  p4: [
    { code: 'aice.9093.p4.world', description: 'Language topics · Section A: English in the world (essay).', count: 1 },
    { code: 'aice.9093.p4.self', description: 'Language topics · Section B: language and the self (essay).', count: 1 },
  ],
};
const ENG_ITEMS: AiceItem[] = [
  { objectiveCode: 'aice.9093.p1.directed', content: rubricItem({ key: 'p1.directed', language: en, stimulus: TRAVEL, tags: T('Directed response', 'AO2'), commandTerm: 'write', question: '(a) Using Text 1, write the opening of a leaflet (150–200 words) encouraging visitors to stay with farming families in the valley. (b) Compare the language and style of your leaflet with Text 1.', explanation: 'A leaflet adapting the content for a persuasive purpose, then a comparison of form, style and language choices.', rubric: rubric('ANALYTIC', [['A', '(a) Directed writing: purpose, audience, form and accuracy', 10, ['Little sense of the task.', 'Some adaptation for purpose and audience.', 'Clear, accurate adaptation.', 'Assured, well-crafted adaptation.']], ['B', '(b) Comparative analysis of form, style and language', 15, ['Little comparison.', 'Some comparison, mostly content.', 'Clear comparison of style and language with examples.', 'Perceptive comparison with precise terminology.']]]), modelAnswerSummary: 'Leaflet: second person, imperatives, positive lexis, headings, selected details (terraces, café, hospitality). Comparison: blog is first-person, reflective, anecdotal, uses humour and dialogue; leaflet is persuasive, direct and informative.' }) },
  { objectiveCode: 'aice.9093.p1.analysis', content: rubricItem({ key: 'p1.analysis', language: en, stimulus: SPEECH, tags: T('Text analysis', 'AO3'), commandTerm: 'analyse', question: 'Analyse how the writer of Text 2 uses form, structure and language to persuade the audience.', explanation: 'Analysis of rhetorical structure (correction, metaphor of borrowing), imperatives, direct address and the ladder image.', rubric: rubric('BEST_FIT', [['A', 'Analysis of form, structure and language choices and their effects', 15, ['Mostly summary.', 'Some features identified.', 'Clear analysis of features and effects.', 'Perceptive analysis of how choices create meaning.']], ['C', 'Understanding of context, audience and purpose', 10, ['Little awareness.', 'Some awareness.', 'Clear awareness shaping the analysis.', 'Sophisticated awareness throughout.']]]), modelAnswerSummary: 'Speech opens by correcting a cliché, extended metaphor of borrowing, triadic imperatives, direct address ("you"), final image of the ladder; suited to a celebratory but reflective school audience.' }) },
  { objectiveCode: 'aice.9093.p2.shorter', content: rubricItem({ key: 'p2.shorter', language: en, tags: T('Shorter writing', 'AO2'), commandTerm: 'write', question: '(a) Write the opening of a short story (no more than 400 words) set in a place that is about to change for ever. (b) Write a reflective commentary on the language choices you made.', explanation: 'An effective story opening and a commentary explaining choices and their intended effects.', rubric: rubric('ANALYTIC', [['A', '(a) Shorter writing: effectiveness, control and accuracy', 15, ['Limited control.', 'Some effective features.', 'Effective, accurate writing.', 'Assured, original and controlled writing.']], ['B', '(b) Reflective commentary on language choices', 10, ['Description of content.', 'Some choices identified.', 'Choices explained with effects.', 'Perceptive explanation of choices and effects.']]]), modelAnswerSummary: 'A focused opening with sensory detail and a hint of change; commentary links choices (tense, imagery, sentence length, point of view) to intended effects.' }) },
  { objectiveCode: 'aice.9093.p2.extended', content: rubricItem({ key: 'p2.extended', language: en, tags: T('Extended writing', 'AO2'), commandTerm: 'write', question: 'Answer ONE (600–900 words): (a) Imaginative: write a story titled "The Last Bus". (b) Discursive: "Teenagers should be allowed to vote at 16." Discuss. (c) Critical: write a review of a film, book or game you know well.', explanation: 'Extended writing appropriate to the chosen form, purpose and audience.', rubric: rubric('BEST_FIT', [['W', 'Content, structure and engagement for the chosen form', 15, ['Undeveloped.', 'Some development and structure.', 'Well developed and structured.', 'Compelling, sophisticated and well structured.']], ['L', 'Language: style, vocabulary and accuracy', 10, ['Frequent errors.', 'Mostly accurate, plain style.', 'Accurate, varied style.', 'Precise, ambitious and accurate style.']]]), modelAnswerSummary: 'A full response in the chosen form with a clear structure, sustained purpose and controlled, accurate style.' }) },
  { objectiveCode: 'aice.9093.p3.change', content: rubricItem({ key: 'p3.change', language: en, stimulus: NGRAM, tags: T('Language change', 'AO5'), commandTerm: 'analyse', question: 'Using the corpus data, analyse how the meaning and use of "awesome" have changed, and explain possible reasons for the change, referring to ideas about language change.', explanation: 'Frequency growth (0.6 to 11.8 per million), semantic shift / bleaching from "inspiring awe" to general approval, collocate change, informalisation and media influence.', rubric: rubric('BEST_FIT', [['D', 'Analysis of the data (frequency, collocation, meaning)', 13, ['Data copied.', 'Some trends noted.', 'Clear analysis of trends and collocates.', 'Precise, insightful analysis of the data.']], ['T', 'Use of concepts and theories of language change', 12, ['No concepts.', 'Some concepts named.', 'Concepts applied to the data.', 'Concepts applied critically and precisely.']]]), modelAnswerSummary: 'Twenty-fold increase, sharp rise after 1980; collocates move from power / responsibility to job / totally: semantic weakening (bleaching) and amelioration into casual approval, informalisation, influence of American media and youth speech.' }) },
  { objectiveCode: 'aice.9093.p3.acquisition', content: rubricItem({ key: 'p3.acquisition', language: en, stimulus: TRANSCRIPT, tags: T('Child language acquisition', 'AO4'), commandTerm: 'analyse', question: 'Analyse the child’s language in the transcript and the role of the parent, referring to ideas about child language acquisition.', explanation: 'Telegraphic speech, overgeneralisation ("goed"), omission of auxiliaries, emerging plural / adjective use; parent recasts and expands (child-directed speech).', rubric: rubric('BEST_FIT', [['L', 'Analysis of the child’s language (grammar, lexis, phonology)', 13, ['Little analysis.', 'Some features noted.', 'Clear analysis with examples.', 'Precise, systematic analysis.']], ['T', 'Use of theories and the role of interaction', 12, ['No theory.', 'Theory named.', 'Theory applied to the transcript.', 'Theories evaluated against the evidence.']]]), modelAnswerSummary: '"goed" = virtuous error / overgeneralisation of past tense; telegraphic utterances ("in car"), omitted auxiliaries / infinitive marker; parent recasts ("Daddy went") and expands, consistent with interactionist views.' }) },
  { objectiveCode: 'aice.9093.p4.world', content: rubricItem({ key: 'p4.world', language: en, tags: T('English in the world', 'AO4'), commandTerm: 'discuss', question: '"English is now a global language that belongs to everyone who uses it." Discuss this view, referring to ideas about English in the world.', explanation: 'An essay weighing world Englishes, ownership, standards and the effects on other languages.', rubric: rubric('BEST_FIT', [['K', 'Knowledge and use of ideas about global English', 13, ['Little knowledge.', 'Some relevant ideas.', 'Clear, relevant ideas with examples.', 'Wide, precise knowledge used critically.']], ['A', 'Argument, evaluation and structure', 12, ['Assertion.', 'Some argument.', 'A clear, evaluative argument.', 'A sustained, nuanced argument.']]]), modelAnswerSummary: 'Kachru’s circles, world Englishes and lingua franca use, debates on standards and ownership, language death / linguistic imperialism; a balanced conclusion.' }) },
  { objectiveCode: 'aice.9093.p4.self', content: rubricItem({ key: 'p4.self', language: en, tags: T('Language and the self', 'AO4'), commandTerm: 'discuss', question: 'Discuss the ways in which the language people use expresses their identity.', explanation: 'An essay on idiolect, sociolect, code-switching, accommodation and identity.', rubric: rubric('BEST_FIT', [['K', 'Knowledge and use of ideas about language and identity', 13, ['Little knowledge.', 'Some relevant ideas.', 'Clear ideas with examples.', 'Wide, precise knowledge used critically.']], ['A', 'Argument, evaluation and structure', 12, ['Assertion.', 'Some argument.', 'A clear, evaluative argument.', 'A sustained, nuanced argument.']]]), modelAnswerSummary: 'Idiolect and sociolect, accent and dialect, code-switching, accommodation theory, online identities; evaluation of how far language constructs or reflects identity.' }) },
];

// ================================================================ 9708 Economics
const SUGAR = { key: 'aice.9708.sugar', title: 'Data — a tax on sugary drinks (StudyUS practice data)', text: 'In Country Z a tax of $0.20 per litre was placed on sugary drinks. In the following year the average price rose from $1.00 to $1.15 per litre and sales fell from 400 to 370 million litres. Tax revenue was spent on school sports.' };
const ECO_OBJ: Record<string, AiceObjective[]> = {
  p1: [
    { code: 'aice.9708.p1.basic-ideas', description: 'Basic economic ideas and resource allocation.', count: 1 },
    { code: 'aice.9708.p1.price-system', description: 'The price system and the microeconomy (elasticity).', count: 1 },
    { code: 'aice.9708.p1.macroeconomy', description: 'The macroeconomy (inflation).', count: 1 },
  ],
  p2: [
    { code: 'aice.9708.p2.data-response', description: 'Data response (Section A).', count: 1 },
    { code: 'aice.9708.p2.micro-essay', description: 'Two-part essay, mainly microeconomics (Section B).', count: 1 },
    { code: 'aice.9708.p2.macro-essay', description: 'Two-part essay, mainly macroeconomics (Section C).', count: 1 },
  ],
  p3: [
    { code: 'aice.9708.p3.market-structure', description: 'The price system and the microeconomy (market structures).', count: 1 },
    { code: 'aice.9708.p3.intervention', description: 'Government microeconomic intervention (externalities).', count: 1 },
    { code: 'aice.9708.p3.international', description: 'International economic issues (exchange rates).', count: 1 },
  ],
  p4: [
    { code: 'aice.9708.p4.data-response', description: 'Data response (Section A).', count: 1 },
    { code: 'aice.9708.p4.micro-essay', description: 'Unstructured micro essay (Section B).', count: 1 },
    { code: 'aice.9708.p4.macro-essay', description: 'Unstructured macro essay (Section C).', count: 1 },
  ],
};
const essay = (k: string, d: string, q: string, model: string) => rubricItem({ key: k, language: en, tags: T(d, 'AO3'), commandTerm: 'evaluate', question: q, explanation: 'Analysis with diagrams where relevant, evaluation and a supported conclusion.', rubric: rubric('BEST_FIT', [['K', 'Knowledge, understanding and analysis (diagrams where relevant)', 12, ['Little relevant knowledge.', 'Some relevant analysis.', 'Clear, accurate analysis.', 'Thorough, precise analysis.']], ['E', 'Evaluation and supported conclusion', 8, ['No evaluation.', 'Some evaluative comments.', 'Clear evaluation.', 'Sustained, well-supported evaluation.']]]), modelAnswerSummary: model });
const ECO_ITEMS: AiceItem[] = [
  { objectiveCode: 'aice.9708.p1.basic-ideas', content: mc({ key: 'p1.opportunity', language: en, tags: T('Basic economic ideas', 'AO1'), question: 'A government spends $5m on a new hospital instead of a new school. What is the opportunity cost of the hospital?', options: ['The school that is not built', 'The $5m spent', 'The wages of the hospital staff', 'The tax raised to pay for it'], correct: 0, explanation: 'Opportunity cost is the next best alternative forgone.' }) },
  { objectiveCode: 'aice.9708.p1.price-system', content: mc({ key: 'p1.ped', language: en, tags: T('Price elasticity of demand', 'AO2'), calculator: 'ALLOWED', question: 'The price of a good rises by 10 % and the quantity demanded falls by 5 %. What is the price elasticity of demand?', options: ['−0.5', '−2.0', '−0.05', '−5.0'], correct: 0, explanation: 'PED = −5 % / 10 % = −0.5 (inelastic).' }) },
  { objectiveCode: 'aice.9708.p1.macroeconomy', content: mc({ key: 'p1.cpi', language: en, tags: T('Inflation', 'AO1'), question: 'A consumer price index rises from 120 to 126. What is the rate of inflation?', options: ['5 %', '6 %', '4.8 %', '126 %'], correct: 0, explanation: '(126 − 120) / 120 × 100 = 5 %.' }) },
  { objectiveCode: 'aice.9708.p2.data-response', content: rubricItem({ key: 'p2.data', language: en, stimulus: SUGAR, tags: T('Data response', 'AO2'), commandTerm: 'calculate', question: '(a) Calculate the price elasticity of demand for sugary drinks using the data. (b) Explain why the price rose by less than the tax. (c) Evaluate whether the tax is likely to achieve its aim of reducing sugar consumption.', explanation: '(a) %ΔQ = −7.5 %, %ΔP = 15 %, PED = −0.5. (b) Incidence is shared between consumers and producers. (c) Inelastic demand, substitutes, regressive effects, use of revenue.', rubric: rubric('ANALYTIC', [['A', '(a) Calculation with working', 4, ['Wrong method.', 'Correct method, arithmetic error.', 'Correct value.', 'Correct value with working and interpretation.']], ['B', '(b) Tax incidence explained', 6, ['Asserted.', 'Partly explained.', 'Explained with reference to elasticity.', 'Explained clearly, possibly with a diagram.']], ['C', '(c) Evaluation with a judgement', 10, ['No evaluation.', 'Some points.', 'Balanced evaluation.', 'Well-supported evaluation and judgement.']]], 3), modelAnswerSummary: 'PED = −7.5 % / 15 % = −0.5; price rose $0.15 of the $0.20 tax because demand is inelastic so consumers bear most of it; consumption fell modestly (7.5 %); effectiveness depends on elasticity, substitutes, regressivity, and the use of revenue for sport.' }) },
  { objectiveCode: 'aice.9708.p2.micro-essay', content: essay('p2.micro', 'Market failure', 'Answer ONE. EITHER (a) Explain how a maximum price can create a shortage, and evaluate whether maximum prices on rented housing benefit tenants. OR (b) Explain what is meant by a merit good, and evaluate the case for providing education free of charge.', 'Maximum price below equilibrium creates excess demand; evaluation: some tenants gain, quality and supply fall, black markets. OR merit good under-consumed due to information failure; free provision raises consumption but has opportunity costs and possible excess demand.') },
  { objectiveCode: 'aice.9708.p2.macro-essay', content: essay('p2.macro', 'Macroeconomic policy', 'Answer ONE. EITHER (a) Explain the causes of demand-pull inflation, and evaluate the use of higher interest rates to reduce it. OR (b) Explain how a depreciation of a currency affects a current account, and evaluate whether depreciation always improves it.', 'Demand-pull from excess aggregate demand; higher rates reduce consumption and investment but with time lags and growth costs. OR depreciation makes exports cheaper and imports dearer; Marshall–Lerner condition and the J-curve mean improvement is not guaranteed.') },
  { objectiveCode: 'aice.9708.p3.market-structure', content: mc({ key: 'p3.monopoly', language: en, tags: T('Market structures', 'AO2'), question: 'A profit-maximising monopolist produces where:', options: ['marginal revenue equals marginal cost', 'price equals marginal cost', 'average revenue equals average cost', 'total revenue is maximised'], correct: 0, explanation: 'Profit is maximised where MR = MC.' }) },
  { objectiveCode: 'aice.9708.p3.intervention', content: mc({ key: 'p3.externality', language: en, tags: T('Externalities', 'AO2'), question: 'A factory pollutes a river. Without intervention, how does the free-market output compare with the socially optimal output?', options: ['It is higher', 'It is lower', 'It is the same', 'It cannot be compared'], correct: 0, explanation: 'Marginal social cost exceeds marginal private cost, so the market over-produces.' }) },
  { objectiveCode: 'aice.9708.p3.international', content: mc({ key: 'p3.exchange', language: en, tags: T('Exchange rates', 'AO2'), question: 'Under a floating exchange rate, which would most likely cause a country’s currency to appreciate?', options: ['A rise in its interest rates relative to other countries', 'A rise in its imports', 'A fall in foreign investment into the country', 'A rise in its inflation relative to other countries'], correct: 0, explanation: 'Higher relative interest rates attract capital inflows, raising demand for the currency.' }) },
  { objectiveCode: 'aice.9708.p4.data-response', content: rubricItem({ key: 'p4.data', language: en, stimulus: { key: 'aice.9708.growth', title: 'Data — Country W (StudyUS practice data)', text: 'Real GDP growth: 2023 4.1 %, 2024 2.0 %, 2025 0.8 %. Unemployment: 2023 4.5 %, 2025 6.9 %. Gini coefficient: 2023 0.34, 2025 0.38. Government budget deficit: 2023 2 % of GDP, 2025 5 % of GDP.' }, tags: T('Data response', 'AO2'), commandTerm: 'evaluate', question: '(a) Describe the trend in real GDP growth. (b) Explain the likely link between the growth figures and unemployment. (c) Evaluate whether a larger budget deficit is the best policy response for Country W.', explanation: 'Slowing growth, cyclical unemployment (Okun), rising inequality; evaluation of fiscal stimulus against debt, crowding out and alternatives.', rubric: rubric('ANALYTIC', [['A', '(a) Trend described with data', 3, ['Inaccurate.', 'Partly described.', 'Described accurately.', 'Described accurately with figures.']], ['B', '(b) Link explained', 7, ['Asserted.', 'Partly explained.', 'Clearly explained.', 'Clearly explained with economic reasoning.']], ['C', '(c) Evaluation with a judgement', 10, ['No evaluation.', 'Some points.', 'Balanced evaluation.', 'Well-supported evaluation and judgement.']]], 3), modelAnswerSummary: 'Growth slowed each year (4.1 → 0.8 %); slower growth reduces derived demand for labour, raising cyclical unemployment; deficit spending can support demand but raises debt, may crowd out, and monetary or supply-side policies are alternatives.' }) },
  { objectiveCode: 'aice.9708.p4.micro-essay', content: essay('p4.micro', 'Labour markets and efficiency', 'Answer ONE. EITHER (a) Assess whether a national minimum wage helps low-paid workers. OR (b) Assess whether perfect competition is always more efficient than monopoly.', 'Minimum wage: higher pay for those employed, possible unemployment depending on elasticity and monopsony. OR allocative / productive efficiency in perfect competition vs dynamic efficiency and economies of scale in monopoly.') },
  { objectiveCode: 'aice.9708.p4.macro-essay', content: essay('p4.macro', 'Economic development', 'Answer ONE. EITHER (a) Assess whether economic growth always improves living standards. OR (b) Assess the effectiveness of supply-side policies in reducing unemployment.', 'Growth and HDI, inequality, externalities and sustainability. OR supply-side policies address structural unemployment with long time lags and limited effect on cyclical unemployment.') },
];

const GPR_FORMATS = { c1: ['EXTENDED_RESPONSE', 'SHORT_RESPONSE'], c2: ['MULTIMODAL_SUBMISSION', 'ESSAY'], c3: ['MULTIMODAL_SUBMISSION'], c4: ['MULTIMODAL_SUBMISSION'] } as never;
const GPR_LIMITS = { c3: ['The team project is done in a team; StudyUS practises the individual presentation and reflective paper. Recordings are never scored by AI: they go to human review.'] };
const ENG_FORMATS = { p1: ['EXTENDED_RESPONSE'], p2: ['EXTENDED_RESPONSE'], p3: ['EXTENDED_RESPONSE'], p4: ['ESSAY'] } as never;
const ECO_FORMATS = { p1: ['SELECTED_RESPONSE'], p2: ['EXTENDED_RESPONSE', 'ESSAY'], p3: ['SELECTED_RESPONSE'], p4: ['EXTENDED_RESPONSE', 'ESSAY'] } as never;
const TERMS = ['identify', 'evaluate', 'research', 'present', 'write', 'analyse', 'discuss', 'calculate'].map((term) => ({ term }));

export const AICE_9239_AS = aiceConfig({ code: '9239', level: 'AS', objectives: GPR_OBJ, items: GPR_ITEMS, responseFormats: GPR_FORMATS, limitations: GPR_LIMITS, commandTerms: TERMS });
export const AICE_9239_A = aiceConfig({ code: '9239', level: 'A', objectives: GPR_OBJ, items: GPR_ITEMS, responseFormats: GPR_FORMATS, limitations: GPR_LIMITS, commandTerms: TERMS });
export const AICE_9093_AS = aiceConfig({ code: '9093', level: 'AS', objectives: ENG_OBJ, items: ENG_ITEMS, responseFormats: ENG_FORMATS, commandTerms: TERMS });
export const AICE_9093_A = aiceConfig({ code: '9093', level: 'A', objectives: ENG_OBJ, items: ENG_ITEMS, responseFormats: ENG_FORMATS, commandTerms: TERMS });
export const AICE_9708_AS = aiceConfig({ code: '9708', level: 'AS', objectives: ECO_OBJ, items: ECO_ITEMS, responseFormats: ECO_FORMATS, commandTerms: TERMS });
export const AICE_9708_A = aiceConfig({ code: '9708', level: 'A', objectives: ECO_OBJ, items: ECO_ITEMS, responseFormats: ECO_FORMATS, commandTerms: TERMS });
