#!/usr/bin/env python3
"""
Exam V2 -- generates src/lib/exam-core/catalog/ib-dp.generated.ts from the reviewed
IB DP research (docs/exams/v2/sources/ib-dp-groups-*.json). The generated file is
typed data only; re-run after the research is updated and review the diff.

  python3 scripts/catalog/generate-ib-dp-catalog.py
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = [os.path.join(ROOT, 'docs/exams/v2/sources', f) for f in ('ib-dp-groups-1-3-core.json', 'ib-dp-groups-4-6.json')]
OUT = os.path.join(ROOT, 'src/lib/exam-core/catalog/ib-dp.generated.ts')

subjects, sources, seen = [], [], set()
for path in SRC:
    d = json.load(open(path))
    for s in d['sources']:
        if s['key'] in seen: continue
        seen.add(s['key'])
        sources.append({'key': s['key'], 'title': s['title'], 'publisher': s.get('publisher') or 'IBO', 'url': s.get('url'), 'year': s.get('year'), 'confidence': s.get('confidence') or 'MEDIUM'})
    for s in d['subjects']:
        comps = []
        for c in s.get('components', []):
            comps.append({k: c.get(k) for k in ('key', 'name', 'type', 'levels', 'minutes', 'marks', 'weightPercent', 'format', 'calculator', 'resources', 'notes')})
        subjects.append({
            'group': str(s['group']), 'key': s['key'], 'name': s['name'], 'curriculumVersion': s.get('curriculumVersion'),
            'firstAssessment': s.get('firstAssessment'), 'lastAssessment': s.get('lastAssessment'), 'levels': s.get('levels', []),
            'components': comps, 'paper1Combined': s.get('paper1Combined'), 'assessmentObjectives': s.get('assessmentObjectives', []),
            'sourceKeys': s.get('sourceKeys', []), 'confidence': s.get('confidence', 'MEDIUM'), 'gaps': s.get('gaps'),
        })

def ts(v): return json.dumps(v, ensure_ascii=False, indent=1)
with open(OUT, 'w') as f:
    f.write('/* eslint-disable */\n/**\n * GENERATED by scripts/catalog/generate-ib-dp-catalog.py from the reviewed IB DP research\n * (docs/exams/v2/sources/ib-dp-groups-*.json, researched 2026-10-01). Do not edit by hand.\n */\n')
    f.write("import type { AssessmentSourceSeed } from './sources';\n\n")
    f.write('export type IbLevel = \'SL\' | \'HL\' | \'CORE\';\n')
    f.write('export interface IbComponentSpec { key: string; name: string; type: string; levels: IbLevel[]; minutes: Partial<Record<IbLevel, number>> | null; marks: Partial<Record<IbLevel, number>> | null; weightPercent: Partial<Record<IbLevel, number>> | null; format: string | null; calculator: string | null; resources: string | null; notes: string | null }\n')
    f.write('export interface IbSubjectSpec { group: string; key: string; name: string; curriculumVersion: string | null; firstAssessment: number | null; lastAssessment: number | null; levels: IbLevel[]; components: IbComponentSpec[]; paper1Combined: { minutes: Partial<Record<IbLevel, number>>; marks: Partial<Record<IbLevel, number>>; weightPercent: Partial<Record<IbLevel, number>> } | null; assessmentObjectives: string[]; sourceKeys: string[]; confidence: \'HIGH\' | \'MEDIUM\' | \'LOW\'; gaps: string | null }\n\n')
    f.write('export const IB_DP_SUBJECTS: IbSubjectSpec[] = ' + ts(subjects) + ' as IbSubjectSpec[];\n\n')
    srcs = [{'key': s['key'], 'framework': 'IB', 'title': s['title'], 'publisher': s['publisher'], 'url': s['url'], 'publicationYear': s['year'], 'confidence': s['confidence'] if s['confidence'] in ('HIGH','MEDIUM','LOW') else 'MEDIUM', 'license': 'PUBLIC'} for s in sources]
    f.write('export const IB_DP_SOURCES: AssessmentSourceSeed[] = ' + ts(srcs) + ' as AssessmentSourceSeed[];\n')
print(f'wrote {OUT}: {len(subjects)} subjects, {len(sources)} sources')
