"""Generates src/lib/exam-core/aice/aice-syllabi.generated.ts from the reviewed
research docs/exams/v2/sources/aice-reference-syllabi.json and aice-diploma.json
(cambridgeinternational.org syllabus PDFs). Structure only -- no questions or
mark schemes. Run: python3 scripts/catalog/generate-aice-syllabi.py"""
import json, os, re
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
syl = json.load(open(os.path.join(root, 'docs/exams/v2/sources/aice-reference-syllabi.json')))
dip = json.load(open(os.path.join(root, 'docs/exams/v2/sources/aice-diploma.json')))
def js(v): return json.dumps(v, ensure_ascii=False)
out = []
sources = []
for s in syl['syllabi']:
    years = s.get('examYears') or []
    m = re.match(r'(\d{4})-(\d{4})', s['version'])
    first, last = (int(m.group(1)), int(m.group(2))) if m else (min(years), max(years))
    vkey = f"{first}-{last}"
    skey = f"cie-{s['code']}-syllabus-{vkey}"
    sources.append({'key': skey, 'framework': 'CAMBRIDGE', 'title': s['sourceTitle'][:200], 'publisher': 'Cambridge International', 'url': s['sourceUrl'], 'documentVersion': s['version'][:100], 'publicationYear': None, 'effectiveSession': f'Examination in {first}-{last}', 'confidence': s['confidence'], 'license': 'PUBLIC'})
    routes = []
    for r in s['routes']:
        key = {'AS_ONLY': 'AS_ONLY', 'A_LINEAR': 'A_LEVEL_LINEAR', 'A_STAGED': 'A_LEVEL_STAGED'}.get(r['key'], 'GOVERNED_COMBINATION')
        stages = None
        if r.get('stages'):
            st = r['stages']
            if st and isinstance(st[0], dict): stages = [[x['as'], x['complete']] for x in st]
            else: stages = [st]
        routes.append({'key': key, 'description': r['description'], 'componentSets': r['componentSets'], 'stages': stages})
    comps = [{k: c.get(k) for k in ('key', 'number', 'name', 'type', 'minutes', 'marks', 'weightAS', 'weightA', 'levels', 'calculator', 'resources', 'questionTypes', 'notes')} for c in s['components']]
    out.append({'code': s['code'], 'title': s['title'], 'version': s['version'], 'versionKey': vkey, 'firstExam': first, 'lastExam': last, 'sourceKey': skey, 'sourceUrl': s['sourceUrl'], 'confidence': s['confidence'], 'components': comps, 'routes': routes,
                'assessmentObjectives': [{'key': a['key'], 'name': a['name'], 'weightAS': a.get('weightAS'), 'weightA': a.get('weightA')} for a in s['assessmentObjectives']], 'topics': s['topics'], 'notes': s.get('notes')})
for src in dip['sources']:
    sources.append({'key': src['key'], 'framework': 'CAMBRIDGE', 'title': src['title'][:200], 'publisher': 'Cambridge International', 'url': src['url'], 'publicationYear': None, 'effectiveSession': (src.get('effective') or '')[:100], 'confidence': src['confidence'], 'license': 'PUBLIC'})
lines = ['/**', ' * GENERATED by scripts/catalog/generate-aice-syllabi.py from docs/exams/v2/sources/aice-reference-syllabi.json', ' * and aice-diploma.json (cambridgeinternational.org, retrieved ' + syl['retrievedAt'] + '). Structure only. Do not edit by hand.', ' */',
         "import type { AssessmentSourceSeed } from '../catalog/sources';", '',
         'export interface AiceSyllabusComponent { key: string; number: string; name: string; type: string; minutes: number | null; marks: number; weightAS: number | null; weightA: number | null; levels: Array<\'AS\' | \'A\'>; calculator: string | null; resources: string | null; questionTypes: string | null; notes: string | null }',
         "export interface AiceSyllabusRoute { key: 'AS_ONLY' | 'A_LEVEL_LINEAR' | 'A_LEVEL_STAGED' | 'GOVERNED_COMBINATION'; description: string; componentSets: string[][]; stages: string[][][] | null }",
         'export interface AiceSyllabus { code: string; title: string; version: string; versionKey: string; firstExam: number; lastExam: number; sourceKey: string; sourceUrl: string; confidence: string; components: AiceSyllabusComponent[]; routes: AiceSyllabusRoute[]; assessmentObjectives: Array<{ key: string; name: string; weightAS: number | null; weightA: number | null }>; topics: Record<string, string[]>; notes: string | null }', '',
         'export const AICE_SYLLABI: AiceSyllabus[] = ' + json.dumps(out, ensure_ascii=False, indent=1) + ';', '',
         'export const AICE_SOURCES: AssessmentSourceSeed[] = ' + json.dumps(sources, ensure_ascii=False, indent=1) + ';', '']
open(os.path.join(root, 'src/lib/exam-core/aice/aice-syllabi.generated.ts'), 'w').write('\n'.join(lines))
print(len(out), 'syllabi', len(sources), 'sources')
