"""Generates src/lib/exam-core/aice/aice-subjects.generated.ts from the reviewed
research docs/exams/v2/sources/aice-diploma.json (cambridgeinternational.org).
Only subjects whose syllabus code was confirmed on a Cambridge page are emitted.
Run: python3 scripts/catalog/generate-aice-catalog.py"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
d = json.load(open(os.path.join(root, 'docs/exams/v2/sources/aice-diploma.json')))
subjects = sorted(d['subjects'], key=lambda s: s['code'])
def js(v): return json.dumps(v, ensure_ascii=False)
lines = ['/**', ' * GENERATED by scripts/catalog/generate-aice-catalog.py from docs/exams/v2/sources/aice-diploma.json', ' * (cambridgeinternational.org, retrieved ' + d['retrievedAt'] + '). Do not edit by hand.', ' */', "import type { SubjectRule } from './diploma';", '',
         'export const AICE_SUBJECTS: Array<SubjectRule & { notes: string | null; sourceKey: string }> = [']
for s in subjects:
    assert s.get('code') and s['code'].isdigit(), s
    lines.append(f"  {{ code: {js(s['code'])}, name: {js(s['name'])}, levels: {js(s['levels'])}, groups: {js(s['groups'])}, notes: {js(s.get('notes') or None)}, sourceKey: {js(s.get('sourceKey') or 'cie-aice-curriculum')} }},")
lines.append('];')
lines.append('')
lines.append('export const AICE_GROUPS: Array<{ key: string; officialName: string }> = ' + js(d['groups']) + ';')
lines.append('')
lines.append('export const AICE_CATALOG_SOURCES: Array<{ key: string; url: string; title: string; effective: string; confidence: string }> = ' + js([{k: s.get(k) for k in ('key','url','title','effective','confidence')} for s in d['sources']]) + ';')
open(os.path.join(root, 'src/lib/exam-core/aice/aice-subjects.generated.ts'), 'w').write('\n'.join(lines) + '\n')
print(len(subjects), 'subjects')
