/**
 * Exam V2 -- writes docs/exams/v2/IB_DP_SUBJECT_READINESS_MATRIX.md from the
 * catalogue + configurations (pure; no database).
 *
 *   npx tsx scripts/operations/track-b-ib-readiness-matrix.ts
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { ibSubjectReadinessMatrix, ibCoverage } from '@/lib/exam-core/catalog/coverage';

const label: Record<string, string> = { CATALOG_ONLY: 'CATALOG_ONLY', STRUCTURE_READY: 'STRUCTURE_READY', PRACTICE_READY: 'PRACTICE_READY', FULL_MOCK_READY: 'FULL_MOCK_READY', NOT_APPLICABLE: '—' };
const rows = ibSubjectReadinessMatrix();
const cov = ibCoverage();
const lines = [
  '# IB Diploma Programme — subject readiness matrix',
  '',
  'Generated by `scripts/operations/track-b-ib-readiness-matrix.ts` from the catalogue and configurations. It is not hand-written.',
  '',
  'Levels show the readiness state. Columns show READY / PARTIAL / NOT_CONFIGURED / NOT_APPLICABLE.',
  '',
  'All content is original StudyUS practice. Official content coverage is 0 %.',
  '',
  '## Coverage',
  '',
  '| Metric | Value |',
  '|---|---|',
  `| IB_DP_CATALOG_COVERAGE | ${cov.catalogPercent} % (${cov.subjects} current subjects / versions) |`,
  `| IB_DP_STRUCTURE_COVERAGE | ${cov.structurePercent} % of ${cov.subjectLevels} examinable subject-levels |`,
  `| IB_DP_PRACTICE_COVERAGE | ${cov.practicePercent} % |`,
  `| IB_DP_FULL_MOCK_COVERAGE | ${cov.fullMockPercent} % (fixed forms; reduced length, disclosed per form) |`,
  '',
  '## Matrix',
  '',
  '| Group | Subject | SL | HL | Current curriculum version | Catalog | Structure | Practice | Full Mock | Learning Bridge | Official content | Source confidence |',
  '|---|---|---|---|---|---|---|---|---|---|---|---|',
  ...rows.map((r) => `| ${r.group} | ${r.subject} | ${label[r.SL]} | ${label[r.HL]} | ${r.version.replace(/\|/g, '/')}${r.lastAssessment ? ` (last ${r.lastAssessment})` : ''} | ${r.catalog} | ${r.structure} | ${r.practice} | ${r.fullMock} | ${r.learningBridge} | ${r.officialContentCoveragePercent} % | ${r.confidence} |`),
  '',
  '**Not catalogued as current:** computer science (legacy), design technology (legacy) and visual arts (legacy), all last assessed in 2026; group 4 school-based syllabuses.',
  '',
];
writeFileSync(join(process.cwd(), 'docs/exams/v2/IB_DP_SUBJECT_READINESS_MATRIX.md'), lines.join('\n'));
console.log(JSON.stringify(cov));
