/**
 * Track A -- Institution workspace manual E2E: operator fixture (DEV ONLY).
 *
 *   prepare   -- an EMPTY institution "TA Manual Institución" with ONE coordinator
 *                (studyus-ta-admin-coord+clerk_test@example.com), plus a teacher account
 *                (studyus-ta-admin-teacher+clerk_test@example.com, TEACHER role, no institution)
 *                and a student account (studyus-ta-admin-student+clerk_test@example.com, STUDENT
 *                role, no class) for the coordinator to invite. Re-running resets the institution
 *                to empty (grades, classes, curriculum, memberships except the coordinator).
 *   evidence  -- READ-ONLY snapshot (grades, classes + curriculum + teacher, memberships, students,
 *                audit actions) for the manual steps.
 *   reset     -- same as prepare's reset (institution back to empty; accounts kept).
 *
 * Never touches any other institution (ALBO included). Sign-in tickets are generated by the team.
 *
 *   npx tsx --env-file=.env.local scripts/operations/track-a-institution-admin-manual-fixture.ts <prepare|evidence|reset>
 */
import { createHash } from 'crypto';
import { createClerkClient } from '@clerk/backend';
import { db } from '@/lib/db';
import { getOrCreateCanonicalUser, assignSelfServiceRole } from '@/lib/identity';
import { upsertStudentFromWebhook } from '@/lib/auth';
import { createInstitution, inviteInstitutionAdmin } from '@/services/institution.service';

const DEV_FP = '2a29b99ee14a22b4';
const DEV_CLERK = 'shining-impala-8101.clerk.accounts.dev';
const INSTITUTION = 'TA Manual Institución';
const ACCOUNTS = {
  coord: { email: 'studyus-ta-admin-coord+clerk_test@example.com', first: 'Carla', last: 'Coordinadora Manual' },
  teacher: { email: 'studyus-ta-admin-teacher+clerk_test@example.com', first: 'Tomás', last: 'Docente Manual' },
  student: { email: 'studyus-ta-admin-student+clerk_test@example.com', first: 'Sara', last: 'Estudiante Manual' },
} as const;

function guard() {
  const u = new URL(process.env.DATABASE_URL ?? '');
  const fp = createHash('sha256').update(u.hostname + '|' + u.pathname.slice(1)).digest('hex').slice(0, 16);
  const pk = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ?? '';
  const inst = Buffer.from(pk.split('_')[2] ?? '', 'base64').toString().replace(/\$$/, '');
  if (fp !== DEV_FP) throw new Error(`REFUSING: DB ${fp}`);
  if (inst !== DEV_CLERK || !(process.env.CLERK_SECRET_KEY ?? '').startsWith('sk_test_')) throw new Error(`REFUSING: Clerk ${inst}`);
}
const clerk = () => createClerkClient({ secretKey: process.env.CLERK_SECRET_KEY! });

async function account(key: keyof typeof ACCOUNTS) {
  const a = ACCOUNTS[key];
  let u = (await clerk().users.getUserList({ emailAddress: [a.email] })).data[0];
  if (!u) u = await clerk().users.createUser({ emailAddress: [a.email], firstName: a.first, lastName: a.last, skipPasswordRequirement: true, publicMetadata: { fixture: 'TRACK_A_INSTITUTION_ADMIN_MANUAL' } });
  const user = await getOrCreateCanonicalUser(u.id, a.email);
  return { clerkId: u.id, userId: user.id, email: a.email };
}

async function institutionId(): Promise<string | null> {
  return (await db.query(`SELECT id FROM institutions WHERE name = $1`, [INSTITUTION])).rows[0]?.id ?? null;
}

/** Back to EMPTY: everything of THIS institution except the coordinator membership (history rows removed: it is a fixture). */
async function reset(inst: string, coordUserId: string) {
  const classes = (await db.query(`SELECT id FROM classes WHERE institution_id = $1`, [inst])).rows.map((r: any) => r.id);
  await db.query(`DELETE FROM academic_governance_events WHERE institution_id = $1`, [inst]);
  await db.query(`DELETE FROM student_concept_sources WHERE institution_id = $1 OR class_id = ANY($2::uuid[])`, [inst, classes]).catch(() => undefined);
  await db.query(`DELETE FROM class_plan_concepts WHERE class_id = ANY($1::uuid[])`, [classes]).catch(() => undefined);
  await db.query(`DELETE FROM institution_assignment_targets WHERE class_id = ANY($1::uuid[])`, [classes]).catch(() => undefined);
  await db.query(`DELETE FROM institution_assignments WHERE institution_id = $1`, [inst]).catch(() => undefined);
  await db.query(`DELETE FROM class_enrollments WHERE class_id = ANY($1::uuid[])`, [classes]);
  await db.query(`DELETE FROM teacher_assignments WHERE class_id = ANY($1::uuid[]) OR grade_id IN (SELECT id FROM grades WHERE institution_id = $2) OR institution_membership_id IN (SELECT id FROM institution_memberships WHERE institution_id = $2)`, [classes, inst]);
  await db.query(`UPDATE classes SET institution_curriculum_id = NULL WHERE institution_id = $1`, [inst]);
  await db.query(`DELETE FROM classes WHERE institution_id = $1`, [inst]);
  for (const t of ['institution_curriculum_objectives', 'institution_curriculum_concepts']) {
    await db.query(`DELETE FROM ${t} WHERE curriculum_id IN (SELECT id FROM institution_curricula WHERE institution_id = $1)`, [inst]).catch(() => undefined);
  }
  await db.query(`UPDATE institution_curricula SET replaced_by_curriculum_id = NULL WHERE institution_id = $1`, [inst]);
  await db.query(`DELETE FROM institution_curriculum_events WHERE institution_id = $1`, [inst]).catch(() => undefined);
  await db.query(`DELETE FROM institution_curricula WHERE institution_id = $1`, [inst]);
  await db.query(`DELETE FROM grades WHERE institution_id = $1`, [inst]);
  await db.query(`DELETE FROM institution_memberships WHERE institution_id = $1 AND NOT (user_id = $2 AND membership_role = 'INSTITUTION_ADMIN')`, [inst, coordUserId]);
  await db.query(`UPDATE institution_memberships SET status = 'APPROVED' WHERE institution_id = $1 AND user_id = $2 AND membership_role = 'INSTITUTION_ADMIN'`, [inst, coordUserId]);
}

async function snapshot(inst: string) {
  const q = async (sql: string) => (await db.query(sql, [inst])).rows;
  return {
    institutionId: inst,
    grades: await q(`SELECT name, academic_level, academic_year, status FROM grades WHERE institution_id = $1 ORDER BY name`),
    classes: await q(
      `SELECT c.name, g.name AS grade, c.academic_domain_code AS domain, c.period, c.status, ic.title AS curriculum,
              (SELECT string_agg(u.email, ', ') FROM teacher_assignments ta JOIN institution_memberships im ON im.id = ta.institution_membership_id JOIN users u ON u.id = im.user_id WHERE ta.class_id = c.id AND ta.status = 'ACTIVE') AS teacher,
              (SELECT count(*) FROM class_enrollments ce WHERE ce.class_id = c.id AND ce.status = 'ACTIVE')::int AS active_students
         FROM classes c LEFT JOIN grades g ON g.id = c.grade_id LEFT JOIN institution_curricula ic ON ic.id = c.institution_curriculum_id
        WHERE c.institution_id = $1 ORDER BY c.name`
    ),
    memberships: await q(`SELECT u.email, im.membership_role, im.status FROM institution_memberships im JOIN users u ON u.id = im.user_id WHERE im.institution_id = $1 ORDER BY im.membership_role, u.email`),
    enrollments: await q(`SELECT s.email, c.name AS class, ce.status FROM class_enrollments ce JOIN classes c ON c.id = ce.class_id JOIN students s ON s.id = ce.student_id WHERE c.institution_id = $1 ORDER BY c.name`),
    auditActions: (await q(`SELECT action, count(*)::int AS n FROM academic_governance_events WHERE institution_id = $1 GROUP BY action ORDER BY action`)).map((r: any) => `${r.action}×${r.n}`),
  };
}

async function main() {
  guard();
  const cmd = process.argv[2];
  if (cmd === 'prepare' || cmd === 'reset') {
    const coord = await account('coord');
    let inst = await institutionId();
    if (!inst) inst = (await createInstitution(INSTITUTION)).id;
    await inviteInstitutionAdmin(inst, coord.userId);
    await reset(inst, coord.userId);
    if (cmd === 'prepare') {
      const teacher = await account('teacher');
      await assignSelfServiceRole(teacher.clerkId, teacher.userId, 'TEACHER');
      const student = await account('student');
      await upsertStudentFromWebhook(student.clerkId, student.email, `${ACCOUNTS.student.first} ${ACCOUNTS.student.last}`);
      await assignSelfServiceRole(student.clerkId, student.userId, 'STUDENT');
      // The student is not in any class of this institution (the coordinator invites her).
      console.log(JSON.stringify({ institution: INSTITUTION, coordinator: coord.email, teacher: teacher.email, student: student.email, baseline: await snapshot(inst) }, null, 2));
      return;
    }
    console.log(JSON.stringify(await snapshot(inst), null, 2));
    return;
  }
  const inst = await institutionId();
  if (!inst) throw new Error('run prepare first');
  if (cmd !== 'evidence') throw new Error('usage: prepare | evidence | reset');
  console.log(JSON.stringify(await snapshot(inst), null, 2));
}
main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exitCode = 1; }).finally(() => db.end());
