/**
 * Generates docs/exams/v2/AICE_SUBJECT_READINESS_MATRIX.md and
 * docs/exams/v2/PISA_DOMAIN_READINESS_MATRIX.md from the catalogue and the
 * configurations (pure: no database). Coverage metrics are kept separate and
 * never folded into one another.
 *
 *   npx tsx scripts/operations/track-b-aice-pisa-matrices.ts
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { parseExamVerticalConfig, type ExamVerticalConfig } from '@/lib/exam-core/vertical-config';
import { allV2Configs } from '@/lib/exam-core/verticals/v2/all';
import { packageReadiness, atLeast, type ReadinessState } from '@/lib/exam-core/catalog/readiness';
import { allLearningLinks } from '@/lib/exam-core/catalog/objective-learning-links';
import { AICE_SUBJECTS } from '@/lib/exam-core/aice/aice-subjects.generated';
import { AICE_SYLLABI } from '@/lib/exam-core/aice/aice-syllabi.generated';

const configs = new Map<string, ExamVerticalConfig>();
for (const v of allV2Configs()) {
  const p = parseExamVerticalConfig(v);
  if (p.ok) configs.set(p.config.key, p.config);
}
const links = allLearningLinks();
const pct = (n: number, d: number) => (d ? Math.round((n / d) * 1000) / 10 : 0);
const bridgeOf = (cfg: ExamVerticalConfig | undefined) => {
  if (!cfg) return 'NOT_CONFIGURED';
  const codes = cfg.sections.flatMap((s) => s.objectives.map((o) => o.code));
  const linked = codes.filter((c) => links[c]?.concepts?.length).length;
  return linked === codes.length ? 'READY' : linked ? 'PARTIAL' : 'NOT_CONFIGURED';
};
const cell = (s: ReadinessState | null, min: ReadinessState) => (s === null ? '—' : atLeast(s, min) ? 'READY' : 'NOT_CONFIGURED');

// ================================================================ AICE
const GROUP_LABEL: Record<string, string> = { CORE: 'Core', GROUP_1: 'Group 1', GROUP_2: 'Group 2', GROUP_3: 'Group 3', GROUP_4: 'Group 4' };
const levelState = (code: string, lv: 'AS' | 'A'): ReadinessState | null => {
  const s = AICE_SUBJECTS.find((x) => x.code === code)!;
  if (!s.levels.includes(lv)) return null;
  const cfg = configs.get(`v2.aice.${code}-${lv === 'AS' ? 'as' : 'a'}`);
  return cfg ? packageReadiness(cfg).state : 'CATALOG_ONLY';
};
const aiceRows = AICE_SUBJECTS.map((s) => {
  const syl = AICE_SYLLABI.find((x) => x.code === s.code);
  const states = (['AS', 'A'] as const).map((lv) => levelState(s.code, lv)).filter((x): x is ReadinessState => x !== null);
  const best = (min: ReadinessState) => (states.every((x) => atLeast(x, min)) ? 'READY' : states.some((x) => atLeast(x, min)) ? 'PARTIAL' : 'NOT_CONFIGURED');
  const bridge = (['AS', 'A'] as const).filter((lv) => s.levels.includes(lv)).map((lv) => bridgeOf(configs.get(`v2.aice.${s.code}-${lv === 'AS' ? 'as' : 'a'}`)));
  return {
    group: s.groups.map((g) => GROUP_LABEL[g]).join(' / '),
    subject: s.name,
    code: s.code,
    as: levelState(s.code, 'AS') ?? '—',
    a: levelState(s.code, 'A') ?? '—',
    version: syl ? `${syl.versionKey} (${syl.version.slice(0, 40)})` : 'not researched',
    structure: best('STRUCTURE_READY'),
    practice: best('PRACTICE_READY'),
    reduced: best('REDUCED_MOCK_READY'),
    full: best('FULL_MOCK_READY'),
    bridge: bridge.every((b) => b === 'READY') ? 'READY' : bridge.some((b) => b !== 'NOT_CONFIGURED') ? 'PARTIAL' : 'NOT_CONFIGURED',
    confidence: syl?.confidence ?? 'HIGH (catalogue only)',
  };
});
const aiceLevels = AICE_SUBJECTS.flatMap((s) => s.levels.map((lv) => levelState(s.code, lv)!));
const aiceBridgeLevels = AICE_SUBJECTS.flatMap((s) => s.levels.map((lv) => bridgeOf(configs.get(`v2.aice.${s.code}-${lv === 'AS' ? 'as' : 'a'}`))));
const aiceCov = {
  AICE_CATALOG_COVERAGE: pct(AICE_SUBJECTS.length, AICE_SUBJECTS.length),
  AICE_STRUCTURE_COVERAGE: pct(aiceLevels.filter((x) => atLeast(x, 'STRUCTURE_READY')).length, aiceLevels.length),
  AICE_PRACTICE_COVERAGE: pct(aiceLevels.filter((x) => atLeast(x, 'PRACTICE_READY')).length, aiceLevels.length),
  AICE_REDUCED_MOCK_COVERAGE: pct(aiceLevels.filter((x) => atLeast(x, 'REDUCED_MOCK_READY')).length, aiceLevels.length),
  AICE_FULL_MOCK_COVERAGE: pct(aiceLevels.filter((x) => x === 'FULL_MOCK_READY').length, aiceLevels.length),
  AICE_LEARNING_BRIDGE_COVERAGE: pct(aiceBridgeLevels.filter((x) => x === 'READY').length, aiceLevels.length),
  OFFICIAL_CONTENT_COVERAGE: 0,
};
const aiceMd = [
  '# Cambridge AICE Diploma — subject readiness matrix',
  '',
  'Generated by `scripts/operations/track-b-aice-pisa-matrices.ts` from the catalogue and the configurations. It is not hand-written.',
  '',
  'Sources:',
  '- Cambridge AICE Diploma qualification and curriculum pages (subjects, codes, groups);',
  '- the syllabus PDFs of the reference subjects (components, marks, timings, routes).',
  '',
  'The denominator is every subject-level the curriculum lists: AS-only subjects count once, AS + A Level subjects twice.',
  '',
  'All items are original StudyUS practice: official content coverage is 0 %.',
  '',
  '## Coverage (separate metrics)',
  '',
  '| Metric | Value |',
  '|---|---|',
  ...Object.entries(aiceCov).map(([k, val]) => `| ${k} | ${val} %${k === 'AICE_CATALOG_COVERAGE' ? ` (${AICE_SUBJECTS.length} subjects, ${aiceLevels.length} subject-levels)` : ''} |`),
  '',
  '## Matrix',
  '',
  '| Group | Subject | Syllabus Code | AS | A Level | Version | Structure | Practice | Reduced Mock | Full Mock | Learning Bridge | Official Content Coverage | Source Confidence |',
  '|---|---|---|---|---|---|---|---|---|---|---|---|---|',
  ...aiceRows.map((r) => `| ${r.group} | ${r.subject} | ${r.code} | ${r.as} | ${r.a} | ${r.version.replace(/\|/g, '/')} | ${r.structure} | ${r.practice} | ${r.reduced} | ${r.full} | ${r.bridge} | 0 % | ${r.confidence} |`),
  '',
].join('\n');

// ================================================================ PISA
const pisa = configs.get('v2.pisa.2022')!;
const pr = packageReadiness(pisa);
const dom = (key: string) => {
  const s = pisa.sections.find((x) => x.key === key)!;
  const items = pisa.items.filter((i) => s.objectives.some((o) => o.code === i.objectiveCode));
  const units = new Set(items.map((i) => i.content.stimulus?.key).filter(Boolean));
  const contexts = new Set(items.map((i) => (i.content.tags?.context ?? '').split(' ·')[0]).filter(Boolean));
  const formats = new Set(items.map((i) => (i.content.rubric ? 'open constructed (partial credit)' : i.content.math ? 'closed constructed (math engine)' : i.content.answerFormat === 'multi_choice' ? 'complex selected' : 'selected')));
  const competencies = s.definition!.distributions[0];
  const covered = s.objectives.filter((o) => items.some((i) => i.objectiveCode === o.code)).length;
  const comp = pr.components.find((c) => c.sectionKey === key)!;
  return { s, items, units, contexts, formats, competencies, covered, comp };
};
const pisaRows = ['math', 'reading', 'science'].map((k) => {
  const d = dom(k);
  const official = d.s.definition!.officialItemCount ?? null;
  return {
    k,
    row: `| 2022 | ${d.s.name} | ${d.s.definition!.officialName} | ${Object.keys(d.competencies.values).join('; ')} | ${[...d.contexts].join(', ') || '—'} | ${d.units.size} units (shared stimulus) | ${[...d.formats].join(', ')} | deterministic + rubric (2 assessors) | ${d.items.length} | ${cell(d.comp.state, 'PRACTICE_READY')} | ${cell(d.comp.state, 'REDUCED_MOCK_READY')} | ${d.comp.state === 'FULL_MOCK_READY' ? 'READY' : 'NOT_READY'} | ${bridgeOf({ ...pisa, sections: [d.s] } as ExamVerticalConfig)} | 0 % | HIGH |`,
    bank: `| ${d.s.name} | ${official ? `${official} per student (official)` : 'not published'} | ${d.comp.requiredPositions} per StudyUS form | ${d.items.length} | ${d.comp.lengthCoveragePercent === null ? 'n/a (official count not published)' : `${d.comp.lengthCoveragePercent} %`} | ${d.units.size} | ${d.covered}/${d.s.objectives.length} | ${d.contexts.size} |`,
  };
});
const pisaCov = {
  PISA_CATALOG_COVERAGE: 100,
  PISA_STRUCTURE_COVERAGE: pct(pr.components.filter((c) => atLeast(c.state, 'STRUCTURE_READY')).length, 3),
  PISA_PRACTICE_COVERAGE: pct(pr.components.filter((c) => atLeast(c.state, 'PRACTICE_READY')).length, 3),
  PISA_REDUCED_SIMULATION_COVERAGE: pct(pr.components.filter((c) => atLeast(c.state, 'REDUCED_MOCK_READY')).length, 3),
  PISA_FULL_SIMULATION_COVERAGE: pct(pr.components.filter((c) => c.state === 'FULL_MOCK_READY').length, 3),
  PISA_LEARNING_BRIDGE_COVERAGE: pct(['math', 'reading', 'science'].filter((k) => bridgeOf({ ...pisa, sections: [pisa.sections.find((x) => x.key === k)!] } as ExamVerticalConfig) === 'READY').length, 3),
  PISA_OFFICIAL_CONTENT_COVERAGE: 0,
};
const pisaMd = [
  '# PISA — domain readiness matrix',
  '',
  'Generated by `scripts/operations/track-b-aice-pisa-matrices.ts` from the configuration. It is not hand-written.',
  '',
  'Frameworks:',
  '- Mathematics: PISA 2022;',
  '- Reading: PISA 2018, reused in 2022;',
  '- Science: PISA 2015, reused in 2022.',
  '',
  'Official items are not reproduced: official content coverage is 0 %. No PISA score, scale or proficiency level is produced.',
  '',
  '## Coverage (separate metrics; denominator = the 3 domains of PISA 2022)',
  '',
  '| Metric | Value |',
  '|---|---|',
  ...Object.entries(pisaCov).map(([k, val]) => `| ${k} | ${val} % |`),
  '',
  '## Matrix',
  '',
  '| Version | Domain | Framework | Competencies | Contexts | Stimulus Types | Item Types | Scoring | Bank Size | Practice | Reduced Simulation | Full Simulation | Learning Bridge | Official Content Coverage | Source Confidence |',
  '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|',
  ...pisaRows.map((r) => r.row),
  '',
  '## Bank coverage',
  '',
  '| Domain | Required target items | Positions | Available valid items | Coverage of official length | Stimulus diversity (units) | Competency coverage | Contexts |',
  '|---|---|---|---|---|---|---|---|',
  ...pisaRows.map((r) => r.bank),
  '',
  'A full simulation would need the 60-minute block of each domain:',
  '- about 30 mathematics items per student (official);',
  '- reading and science item counts per student are not published, so StudyUS cannot declare full length for them.',
  '',
].join('\n');

const dir = join(process.cwd(), 'docs/exams/v2');
writeFileSync(join(dir, 'AICE_SUBJECT_READINESS_MATRIX.md'), aiceMd);
writeFileSync(join(dir, 'PISA_DOMAIN_READINESS_MATRIX.md'), pisaMd);
console.log(JSON.stringify({ aice: aiceCov, pisa: pisaCov }));
