/**
 * LX-4P-PERF-R1D -- interactive formula off the MODEL critical path.
 *
 * MODEL must render as soon as the MODEL-required explanation is ready.
 * The OPTIONAL interactive-formula widget:
 *  - is generated by its own client request lifecycle, never on the
 *    explanation endpoint's response path;
 *  - never gates MODEL availability (no spinner, no error state);
 *  - is inserted progressively when it arrives;
 *  - is routed through the central capability registry (Luna), not a
 *    hard-coded gpt-5.6.
 *
 * Source-contract checks (jsdom-free, like the other perf suites) plus a
 * behavioural unit test of the eligibility gate.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

const read = (p: string) => readFileSync(join(process.cwd(), p), 'utf-8');
const TEACH = read('src/app/dashboard/quiz/TeachingIntro.tsx');
const HOOK = read('src/lib/hooks/useInteractiveFormula.ts');
const FORMULA_SVC = read('src/services/interactive-formula.service.ts');
const EXPL_SVC = read('src/services/concept-explanation.service.ts');
const EXPL_ROUTE = read('src/app/api/concepts/[id]/explanation/route.ts');
const FORMULA_ROUTE = read('src/app/api/concepts/[id]/interactive-formula/route.ts');

/* ---------- R3: server -- formula is OFF the explanation critical path ---------- */
describe('R1D R3 -- the explanation endpoint returns without generating the formula widget', () => {
  it('getConceptExplanation no longer awaits generateInteractiveFormula on the response path', () => {
    const fn = EXPL_SVC.slice(
      EXPL_SVC.indexOf('export async function getConceptExplanation'),
      EXPL_SVC.indexOf('export async function getInteractiveFormula'),
    );
    expect(fn).not.toMatch(/await generateInteractiveFormula/);
    // it still records the eligibility flag + hint for the deferred request
    expect(fn).toMatch(/explanation\.hasFormula\s*=/);
    expect(fn).toMatch(/explanation\.formulaHint\s*=/);
  });

  it('the deferred widget has its own service function and its own route', () => {
    expect(EXPL_SVC).toMatch(/export async function getInteractiveFormula\(/);
    expect(FORMULA_ROUTE).toMatch(/getInteractiveFormula\(studentId, id, language\)/);
    expect(FORMULA_ROUTE).toMatch(/export async function GET\(/);
    // the route file physically lives at the interactive-formula path
    expect(() => read('src/app/api/concepts/[id]/interactive-formula/route.ts')).not.toThrow();
  });

  it('the formula route is a real GET request handler, not a fire-and-forget server promise', () => {
    expect(FORMULA_ROUTE).toMatch(/export async function GET\(/);
    // no unawaited background promise pattern in the explanation service
    expect(EXPL_SVC).not.toMatch(/void generateInteractiveFormula/);
    expect(EXPL_SVC).not.toMatch(/generateInteractiveFormula\([^)]*\)\s*;\s*\n\s*(?!\s*(const|let|var|return|if|\}))/);
  });

  it('the explanation route is unchanged in shape (still one getConceptExplanation call)', () => {
    expect(EXPL_ROUTE).toMatch(/getConceptExplanation\(studentId, id, language\)/);
    expect(EXPL_ROUTE).not.toMatch(/interactive-formula|getInteractiveFormula/);
  });
});

/* ---------- R4: client progressive enhancement ---------- */
describe('R1D R4 -- MODEL renders when explanation is ready; the widget is progressive', () => {
  it('the widget fetch is a separate effect/hook, gated on the explanation already being ready', () => {
    expect(TEACH).toMatch(/useInteractiveFormula\(/);
    expect(TEACH).toMatch(/wantsFormula && !!explanation/); // fires only AFTER explanation
  });

  it('the whole-component loading gate still blocks ONLY on the explanation, never on the widget', () => {
    expect(TEACH).toMatch(/\/\/ Block only on the FIRST needed content \(explanation\)\.[\s\S]*?if \(expLoading\) \{/);
    // no loading/error branch keyed on the formula widget
    expect(TEACH).not.toMatch(/formulaLoading|widgetLoading|formulaError|widgetError/);
  });

  it('the widget renders only once it has arrived -- plain conditional, no spinner, no error state', () => {
    expect(TEACH).toMatch(/\{interactiveFormula && \(\s*\n\s*<div[^>]*>\s*\n\s*<InteractiveFormulaWidget/);
  });

  it('the widget sits INSIDE the MODEL stage block (progressive insert, MODEL not reset)', () => {
    const model = TEACH.slice(TEACH.indexOf("stage === 'MODEL' && explanation"), TEACH.indexOf("stage === 'GUIDE'"));
    expect(model).toMatch(/<InteractiveFormulaWidget/);
  });

  it('R5 (test 5) -- the hook cannot double-fire from effect re-runs / StrictMode', () => {
    expect(HOOK).toMatch(/attemptedRef/);
    expect(HOOK).toMatch(/if \(attemptedRef\.current === key\) return/);
  });
});

/* ---------- R5/R6: model routing + budget ---------- */
describe('R1D R5/R6 -- the formula widget uses centralized routing and a bounded budget', () => {
  it('interactive-formula.service.ts carries no generic gpt-5.6 model literal', () => {
    expect(FORMULA_SVC).not.toMatch(/['"`]gpt-5\.6['"`]/);
    expect(FORMULA_SVC).not.toMatch(/model:\s*['"`]gpt-5\.6['"`]/);
  });

  it('it resolves the model from the capability registry and calls callModel', () => {
    expect(FORMULA_SVC).toMatch(/resolveModels\(prompt\.capability\)/);
    expect(FORMULA_SVC).toMatch(/callModel\(/);
    expect(FORMULA_SVC).not.toMatch(/callOpenAIChat/);
  });

  it('CONTENT_GENERATION routes to Luna (the widget primary)', async () => {
    const { resolveModels } = await import('@/lib/ai/model-routing');
    expect(resolveModels('CONTENT_GENERATION').primary).toBe('gpt-5.6-luna');
  });

  it('the interactive_formula token budget is bounded', async () => {
    const { budgetFor } = await import('@/lib/ai/token-budgets');
    const b = budgetFor('interactive_formula');
    expect(b.maxOutputTokens).toBeGreaterThan(0);
    expect(b.maxOutputTokens).toBeLessThanOrEqual(2000);
    expect(FORMULA_SVC).toMatch(/budgetFor\('interactive_formula'\)/);
  });

  it('the prompt registry entry is CONTENT_GENERATION', async () => {
    const { PROMPT_REGISTRY } = await import('@/lib/ai/prompt-registry');
    expect(PROMPT_REGISTRY['formula.interactive_widget'].capability).toBe('CONTENT_GENERATION');
  });
});

/* R6 eligibility (behavioural, provider-neutral) is in
 * tests/unit/lx4p-perf-r1d-formula-eligibility.test.ts -- it
 * whole-module-mocks @/lib/db, which this source-audit file must not. */

/* ---------- R7: observability ---------- */
describe('R1D R7 -- distinct perf marks; formula timing excluded from MODEL TTFI', () => {
  it('the four marks exist and belong to the right layers', () => {
    expect(TEACH).toContain("'EXPLANATION_READY'");
    expect(TEACH).toContain("'MODEL_RENDERED'");
    expect(HOOK).toContain("'FORMULA_WIDGET_REQUEST_STARTED'");
    expect(HOOK).toContain("'FORMULA_WIDGET_READY'");
    // the two formula marks live in the hook, not the explanation effect
    expect(TEACH).not.toContain('FORMULA_WIDGET_REQUEST_STARTED');
  });
  it('existing T0..T6 journey marks in the quiz page are untouched', () => {
    const QUIZ = read('src/app/dashboard/quiz/page.tsx');
    for (const m of ['T0_start', 'T1_teachingintent_ready', 'T4_gen_start', 'T5_gen_ready', 'T6_first_practice_question']) {
      expect(QUIZ).toContain(`'${m}'`);
    }
  });
});

/* ---------- R8 (tests 8-11): invariants preserved ---------- */
describe('R1D -- language / ordering / background generation / evidence untouched', () => {
  it('test 8 -- activity language flows to both the explanation and the formula fetch', () => {
    expect(TEACH).toMatch(/\/api\/concepts\/\$\{conceptId\}\/explanation\?studentId=\$\{studentId\}&language=\$\{locale\}/);
    expect(HOOK).toMatch(/language=\$\{language\}/);
    expect(TEACH).toMatch(/useInteractiveFormula\(\s*\n?\s*conceptId,\s*\n?\s*studentId,\s*\n?\s*locale,/);
  });

  it('test 9 -- MODEL / GUIDE stage ordering logic is unchanged', () => {
    expect(TEACH).toMatch(/const stages: IntroStage\[\] = view\.stages\.filter\(/);
    expect(TEACH).toMatch(/const plan = stages\.filter\(\(s\) => \(s === 'MODEL' \? view\.showWorkedExample : true\)\)/);
    expect(TEACH).toMatch(/const guidePending = needsGuided && gpLoading/);
  });

  it('test 10 -- the background question-generation architecture is untouched', () => {
    const QUIZ = read('src/app/dashboard/quiz/page.tsx');
    expect(QUIZ).toMatch(/wave B -- question generation, in the background/);
    expect(QUIZ).toMatch(/\/api\/quizzes\/generate-and-take/);
  });

  it('test 11 -- getInteractiveFormula touches no evidence / mastery / learning_evidence surface', () => {
    const fn = EXPL_SVC.slice(EXPL_SVC.indexOf('export async function getInteractiveFormula'));
    expect(fn).not.toMatch(/learning_evidence|knowledge_state|mastery|EvidenceMode|recordEvidence/i);
    // only reads concepts/subjects + concept_explanations
    expect(fn).not.toMatch(/INSERT INTO (?!concept_explanations)/);
  });
});
