/**
 * GENERATED by scripts/catalog/generate-aice-syllabi.py from docs/exams/v2/sources/aice-reference-syllabi.json
 * and aice-diploma.json (cambridgeinternational.org, retrieved 2026-10-01). Structure only. Do not edit by hand.
 */
import type { AssessmentSourceSeed } from '../catalog/sources';

export interface AiceSyllabusComponent { key: string; number: string; name: string; type: string; minutes: number | null; marks: number; weightAS: number | null; weightA: number | null; levels: Array<'AS' | 'A'>; calculator: string | null; resources: string | null; questionTypes: string | null; notes: string | null }
export interface AiceSyllabusRoute { key: 'AS_ONLY' | 'A_LEVEL_LINEAR' | 'A_LEVEL_STAGED' | 'GOVERNED_COMBINATION'; description: string; componentSets: string[][]; stages: string[][][] | null }
export interface AiceSyllabus { code: string; title: string; version: string; versionKey: string; firstExam: number; lastExam: number; sourceKey: string; sourceUrl: string; confidence: string; components: AiceSyllabusComponent[]; routes: AiceSyllabusRoute[]; assessmentObjectives: Array<{ key: string; name: string; weightAS: number | null; weightA: number | null }>; topics: Record<string, string[]>; notes: string | null }

export const AICE_SYLLABI: AiceSyllabus[] = [
 {
  "code": "9709",
  "title": "Cambridge International AS & A Level Mathematics",
  "version": "2026-2027 syllabus, Version 4 (Dec 2025)",
  "versionKey": "2026-2027",
  "firstExam": 2026,
  "lastExam": 2027,
  "sourceKey": "cie-9709-syllabus-2026-2027",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "p1",
    "number": "1",
    "name": "Pure Mathematics 1",
    "type": "WRITTEN_PAPER",
    "minutes": 110,
    "marks": 75,
    "weightAS": 60,
    "weightA": 30,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Scientific calculator required; graphical/symbolic (CAS) calculators and computers not permitted.",
    "resources": "List of formulae and statistical tables (MF19).",
    "questionTypes": "10 to 12 structured questions.",
    "notes": "Compulsory for AS and A Level."
   },
   {
    "key": "p2",
    "number": "2",
    "name": "Pure Mathematics 2",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 50,
    "weightAS": 40,
    "weightA": null,
    "levels": [
     "AS"
    ],
    "calculator": "Scientific calculator required; graphical/CAS not permitted.",
    "resources": "MF19",
    "questionTypes": "6 to 8 structured questions.",
    "notes": "Offered only as part of AS Level; P1+P2 route cannot count towards A Level."
   },
   {
    "key": "p3",
    "number": "3",
    "name": "Pure Mathematics 3",
    "type": "WRITTEN_PAPER",
    "minutes": 110,
    "marks": 75,
    "weightAS": null,
    "weightA": 30,
    "levels": [
     "A"
    ],
    "calculator": "Scientific calculator required; graphical/CAS not permitted.",
    "resources": "MF19",
    "questionTypes": "9 to 11 structured questions.",
    "notes": "Compulsory for A Level."
   },
   {
    "key": "p4",
    "number": "4",
    "name": "Mechanics",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 50,
    "weightAS": 40,
    "weightA": 20,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Scientific calculator required; graphical/CAS not permitted.",
    "resources": "MF19",
    "questionTypes": "6 to 8 structured questions.",
    "notes": "Offered as part of AS and A Level."
   },
   {
    "key": "p5",
    "number": "5",
    "name": "Probability & Statistics 1",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 50,
    "weightAS": 40,
    "weightA": 20,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Scientific calculator required; graphical/CAS not permitted.",
    "resources": "MF19",
    "questionTypes": "6 to 8 structured questions.",
    "notes": "Compulsory for A Level."
   },
   {
    "key": "p6",
    "number": "6",
    "name": "Probability & Statistics 2",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 50,
    "weightAS": null,
    "weightA": 20,
    "levels": [
     "A"
    ],
    "calculator": "Scientific calculator required; graphical/CAS not permitted.",
    "resources": "MF19",
    "questionTypes": "6 to 8 structured questions.",
    "notes": "Offered only as part of A Level; cannot be combined with Paper 4 (depends on Paper 5 content)."
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; two components in the same series. P1+P2 (pure only) cannot count towards A Level.",
    "componentSets": [
     [
      "p1",
      "p2"
     ],
     [
      "p1",
      "p4"
     ],
     [
      "p1",
      "p5"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "Year 1 AS (P1+P4 or P1+P5), carry forward AS result; Year 2 two more components in another series.",
    "componentSets": [
     [
      "p1",
      "p4",
      "p3",
      "p5"
     ],
     [
      "p1",
      "p5",
      "p3",
      "p4"
     ],
     [
      "p1",
      "p5",
      "p3",
      "p6"
     ]
    ],
    "stages": [
     [
      [
       "p1",
       "p4"
      ],
      [
       "p3",
       "p5"
      ]
     ],
     [
      [
       "p1",
       "p5"
      ],
      [
       "p3",
       "p4"
      ]
     ],
     [
      [
       "p1",
       "p5"
      ],
      [
       "p3",
       "p6"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "All four A Level components in the same series.",
    "componentSets": [
     [
      "p1",
      "p3",
      "p4",
      "p5"
     ],
     [
      "p1",
      "p3",
      "p5",
      "p6"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Knowledge and understanding",
    "weightAS": 55,
    "weightA": 52
   },
   {
    "key": "AO2",
    "name": "Application and communication",
    "weightAS": 45,
    "weightA": 48
   }
  ],
  "topics": {
   "AS": [
    "Pure Mathematics 1 (P1): Quadratics; Functions; Coordinate geometry; Circular measure; Trigonometry; Series; Differentiation; Integration",
    "Pure Mathematics 2 (P2): Algebra; Logarithmic and exponential functions; Trigonometry; Differentiation; Integration; Numerical solution of equations",
    "Mechanics (P4): Forces and equilibrium; Kinematics of motion in a straight line; Momentum; Newton's laws of motion; Energy, work and power",
    "Probability & Statistics 1 (P5): Representation of data; Permutations and combinations; Probability; Discrete random variables; The normal distribution"
   ],
   "A": [
    "Pure Mathematics 3 (P3): Algebra; Logarithmic and exponential functions; Trigonometry; Differentiation; Integration; Numerical solution of equations; Vectors; Differential equations; Complex numbers",
    "Probability & Statistics 2 (P6): The Poisson distribution; Linear combinations of random variables; Continuous random variables; Sampling and estimation; Hypothesis tests",
    "Plus P1 and P4/P5 as applicable to the chosen route"
   ]
  },
  "notes": "Mathematics components are not tied to AS vs A Level content halves: P4 and P5 are usable at both levels. Answers on question paper; 3 s.f. unless stated. Ruler and scientific calculator required. A 2028-2030 syllabus exists but 2026-2027 governs 2027 exams."
 },
 {
  "code": "9702",
  "title": "Cambridge International AS & A Level Physics",
  "version": "2025-2027 syllabus (covers examination in 2027)",
  "versionKey": "2025-2027",
  "firstExam": 2025,
  "lastExam": 2027,
  "sourceKey": "cie-9702-syllabus-2025-2027",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/664565-2025-2027-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "p1",
    "number": "1",
    "name": "Multiple Choice",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 40,
    "weightAS": 31,
    "weightA": 15.5,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "No explicit calculator policy statement in syllabus; Mathematical requirements expect candidates to 'use a calculator' for arithmetic, powers, trig and inverses. Treat as scientific calculator (general Cambridge regulations).",
    "resources": "Data and formulae printed in the question paper (page 2 of Papers 1 and 2; page 2 or pages 2–3 of Paper 4 – syllabus wording differs between sections).",
    "questionTypes": "40 four-choice multiple-choice questions; AS Level content; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p2",
    "number": "2",
    "name": "AS Level Structured Questions",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 60,
    "weightAS": 46,
    "weightA": 23,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "No explicit calculator policy statement in syllabus; Mathematical requirements expect candidates to 'use a calculator' for arithmetic, powers, trig and inverses. Treat as scientific calculator (general Cambridge regulations).",
    "resources": "Data and formulae printed in the question paper (page 2 of Papers 1 and 2; page 2 or pages 2–3 of Paper 4 – syllabus wording differs between sections).",
    "questionTypes": "Structured questions; AS Level content; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p3",
    "number": "3",
    "name": "Advanced Practical Skills",
    "type": "PRACTICAL",
    "minutes": 120,
    "marks": 40,
    "weightAS": 23,
    "weightA": 11.5,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "No explicit calculator policy statement in syllabus; Mathematical requirements expect candidates to 'use a calculator' for arithmetic, powers, trig and inverses. Treat as scientific calculator (general Cambridge regulations).",
    "resources": "Laboratory apparatus per confidential instructions (NOT_CONFIRMED detail).",
    "questionTypes": "Practical work and structured questions; AO3 only. Two questions assessing AS practical skills.",
    "notes": ""
   },
   {
    "key": "p4",
    "number": "4",
    "name": "A Level Structured Questions",
    "type": "WRITTEN_PAPER",
    "minutes": 120,
    "marks": 100,
    "weightAS": null,
    "weightA": 38.5,
    "levels": [
     "A"
    ],
    "calculator": "No explicit calculator policy statement in syllabus; Mathematical requirements expect candidates to 'use a calculator' for arithmetic, powers, trig and inverses. Treat as scientific calculator (general Cambridge regulations).",
    "resources": "Data and formulae printed in the question paper (page 2 of Papers 1 and 2; page 2 or pages 2–3 of Paper 4 – syllabus wording differs between sections).",
    "questionTypes": "Structured questions; A Level content, AS knowledge required; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p5",
    "number": "5",
    "name": "Planning, Analysis and Evaluation",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 30,
    "weightAS": null,
    "weightA": 11.5,
    "levels": [
     "A"
    ],
    "calculator": "No explicit calculator policy statement in syllabus; Mathematical requirements expect candidates to 'use a calculator' for arithmetic, powers, trig and inverses. Treat as scientific calculator (general Cambridge regulations).",
    "resources": "NOT_CONFIRMED whether data and formulae are printed in Paper 5.",
    "questionTypes": "Two compulsory questions; AO3 only; context may be outside syllabus content.",
    "notes": ""
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; all AS components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "A Level staged over two years: AS components in Year 1 (AS result carried forward per Cambridge Handbook rules), remaining components in a later series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
     ]
    ],
    "stages": [
     [
      [
       "p1",
       "p2",
       "p3"
      ],
      [
       "p4",
       "p5"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "A Level; all components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Knowledge and understanding",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO2",
    "name": "Handling, applying and evaluating information",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO3",
    "name": "Experimental skills and investigations",
    "weightAS": 20,
    "weightA": 20
   }
  ],
  "topics": {
   "AS": [
    "Physical quantities and units",
    "Kinematics",
    "Dynamics",
    "Forces, density and pressure",
    "Work, energy and power",
    "Deformation of solids",
    "Waves",
    "Superposition",
    "Electricity",
    "D.C. circuits",
    "Particle physics",
    "Practical skills (AS)"
   ],
   "A": [
    "Motion in a circle",
    "Gravitational fields",
    "Temperature",
    "Ideal gases",
    "Thermodynamics",
    "Oscillations",
    "Electric fields",
    "Capacitance",
    "Magnetic fields",
    "Alternating currents",
    "Quantum physics",
    "Nuclear physics",
    "Medical physics",
    "Astronomy and cosmology",
    "Practical skills (A Level)"
   ]
  },
  "notes": "A new 2028-2030 syllabus is published but not used. June and November series (March for India). Practical skills also studied at both levels."
 },
 {
  "code": "9701",
  "title": "Cambridge International AS & A Level Chemistry",
  "version": "2025-2027 syllabus (covers examination in 2027)",
  "versionKey": "2025-2027",
  "firstExam": 2025,
  "lastExam": 2027,
  "sourceKey": "cie-9701-syllabus-2025-2027",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/664563-2025-2027-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "p1",
    "number": "1",
    "name": "Multiple Choice",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 40,
    "weightAS": 31,
    "weightA": 15.5,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Syllabus: 'If calculators are to be used' suggested functions +, –, ×, ÷, √x, x², x^y, log x, ln x, x³, ∛x (scientific).",
    "resources": "Syllabus contains a Data section (constants, ionisation energies, bond energies, E⦵ values, electronegativities, NMR/IR tables, Periodic Table). NOT_CONFIRMED which papers print which tables.",
    "questionTypes": "40 four-choice multiple-choice questions; AS Level content; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p2",
    "number": "2",
    "name": "AS Level Structured Questions",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 60,
    "weightAS": 46,
    "weightA": 23,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Syllabus: 'If calculators are to be used' suggested functions +, –, ×, ÷, √x, x², x^y, log x, ln x, x³, ∛x (scientific).",
    "resources": "Syllabus contains a Data section (constants, ionisation energies, bond energies, E⦵ values, electronegativities, NMR/IR tables, Periodic Table). NOT_CONFIRMED which papers print which tables.",
    "questionTypes": "Structured questions; AS Level content; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p3",
    "number": "3",
    "name": "Advanced Practical Skills",
    "type": "PRACTICAL",
    "minutes": 120,
    "marks": 40,
    "weightAS": 23,
    "weightA": 11.5,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Syllabus: 'If calculators are to be used' suggested functions +, –, ×, ÷, √x, x², x^y, log x, ln x, x³, ∛x (scientific).",
    "resources": "Laboratory apparatus per confidential instructions (NOT_CONFIRMED detail).",
    "questionTypes": "Practical work and structured questions; AO3 only.",
    "notes": ""
   },
   {
    "key": "p4",
    "number": "4",
    "name": "A Level Structured Questions",
    "type": "WRITTEN_PAPER",
    "minutes": 120,
    "marks": 100,
    "weightAS": null,
    "weightA": 38.5,
    "levels": [
     "A"
    ],
    "calculator": "Syllabus: 'If calculators are to be used' suggested functions +, –, ×, ÷, √x, x², x^y, log x, ln x, x³, ∛x (scientific).",
    "resources": "Syllabus contains a Data section (constants, ionisation energies, bond energies, E⦵ values, electronegativities, NMR/IR tables, Periodic Table). NOT_CONFIRMED which papers print which tables.",
    "questionTypes": "Structured questions; A Level content, AS knowledge required; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p5",
    "number": "5",
    "name": "Planning, Analysis and Evaluation",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 30,
    "weightAS": null,
    "weightA": 11.5,
    "levels": [
     "A"
    ],
    "calculator": "Syllabus: 'If calculators are to be used' suggested functions +, –, ×, ÷, √x, x², x^y, log x, ln x, x³, ∛x (scientific).",
    "resources": "NOT_CONFIRMED",
    "questionTypes": "Written; AO3 only (planning, analysis, evaluation); context may be outside syllabus content.",
    "notes": ""
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; all AS components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "A Level staged over two years: AS components in Year 1 (AS result carried forward per Cambridge Handbook rules), remaining components in a later series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
     ]
    ],
    "stages": [
     [
      [
       "p1",
       "p2",
       "p3"
      ],
      [
       "p4",
       "p5"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "A Level; all components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Knowledge and understanding",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO2",
    "name": "Handling, applying and evaluating information",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO3",
    "name": "Experimental skills and investigations",
    "weightAS": 20,
    "weightA": 20
   }
  ],
  "topics": {
   "AS": [
    "Physical chemistry: 1 Atomic structure; 2 Atoms, molecules and stoichiometry; 3 Chemical bonding; 4 States of matter; 5 Chemical energetics; 6 Electrochemistry; 7 Equilibria; 8 Reaction kinetics",
    "Inorganic chemistry: 9 The Periodic Table: chemical periodicity; 10 Group 2; 11 Group 17; 12 Nitrogen and sulfur",
    "Organic chemistry: 13 An introduction to AS Level organic chemistry; 14 Hydrocarbons; 15 Halogen compounds; 16 Hydroxy compounds; 17 Carbonyl compounds; 18 Carboxylic acids and derivatives; 19 Nitrogen compounds; 20 Polymerisation; 21 Organic synthesis",
    "Analysis: 22 Analytical techniques",
    "Practical skills (AS)"
   ],
   "A": [
    "Physical chemistry: 23 Chemical energetics; 24 Electrochemistry; 25 Equilibria; 26 Reaction kinetics",
    "Inorganic chemistry: 27 Group 2; 28 Chemistry of transition elements",
    "Organic chemistry: 29 An introduction to A Level organic chemistry; 30 Hydrocarbons; 31 Halogen compounds; 32 Hydroxy compounds; 33 Carboxylic acids and derivatives; 34 Nitrogen compounds; 35 Polymerisation; 36 Organic synthesis",
    "Analysis: 37 Analytical techniques",
    "Practical skills (A Level)"
   ]
  },
  "notes": "A new 2028-2030 syllabus is published but not used. June and November series (March for India). Practical skills also studied at both levels."
 },
 {
  "code": "9700",
  "title": "Cambridge International AS & A Level Biology",
  "version": "2025-2027 syllabus (covers examination in 2027)",
  "versionKey": "2025-2027",
  "firstExam": 2025,
  "lastExam": 2027,
  "sourceKey": "cie-9700-syllabus-2025-2027",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/664560-2025-2027-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "p1",
    "number": "1",
    "name": "Multiple Choice",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 40,
    "weightAS": 31,
    "weightA": 15.5,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Syllabus: electronic calculators allowed as long as permitted by Cambridge International general regulations.",
    "resources": "No general data booklet stated.",
    "questionTypes": "40 four-choice multiple-choice questions; AS Level content; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p2",
    "number": "2",
    "name": "AS Level Structured Questions",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 60,
    "weightAS": 46,
    "weightA": 23,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Syllabus: electronic calculators allowed as long as permitted by Cambridge International general regulations.",
    "resources": "No general data booklet stated.",
    "questionTypes": "Structured questions; AS Level content; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p3",
    "number": "3",
    "name": "Advanced Practical Skills",
    "type": "PRACTICAL",
    "minutes": 120,
    "marks": 40,
    "weightAS": 23,
    "weightA": 11.5,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Syllabus: electronic calculators allowed as long as permitted by Cambridge International general regulations.",
    "resources": "Laboratory apparatus per confidential instructions (NOT_CONFIRMED detail).",
    "questionTypes": "Practical work and structured questions; AO3 only. Includes use of a light microscope.",
    "notes": ""
   },
   {
    "key": "p4",
    "number": "4",
    "name": "A Level Structured Questions",
    "type": "WRITTEN_PAPER",
    "minutes": 120,
    "marks": 100,
    "weightAS": null,
    "weightA": 38.5,
    "levels": [
     "A"
    ],
    "calculator": "Syllabus: electronic calculators allowed as long as permitted by Cambridge International general regulations.",
    "resources": "A Level statistical formulae provided as shown in the syllabus Mathematical requirements.",
    "questionTypes": "Structured questions; A Level content, AS knowledge required; AO1+AO2.",
    "notes": ""
   },
   {
    "key": "p5",
    "number": "5",
    "name": "Planning, Analysis and Evaluation",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 30,
    "weightAS": null,
    "weightA": 11.5,
    "levels": [
     "A"
    ],
    "calculator": "Syllabus: electronic calculators allowed as long as permitted by Cambridge International general regulations.",
    "resources": "A Level statistics formulae (chi-squared, t-test, Hardy–Weinberg, Simpson's index, correlation) will be provided as shown in Mathematical requirements; Papers 4 and 5 may require completing partly worked calculations.",
    "questionTypes": "Written; AO3 only (planning, analysis, evaluation); context may be outside syllabus content.",
    "notes": ""
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; all AS components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "A Level staged over two years: AS components in Year 1 (AS result carried forward per Cambridge Handbook rules), remaining components in a later series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
     ]
    ],
    "stages": [
     [
      [
       "p1",
       "p2",
       "p3"
      ],
      [
       "p4",
       "p5"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "A Level; all components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Knowledge and understanding",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO2",
    "name": "Handling, applying and evaluating information",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO3",
    "name": "Experimental skills and investigations",
    "weightAS": 20,
    "weightA": 20
   }
  ],
  "topics": {
   "AS": [
    "Cell structure",
    "Biological molecules",
    "Enzymes",
    "Cell membranes and transport",
    "The mitotic cell cycle",
    "Nucleic acids and protein synthesis",
    "Transport in plants",
    "Transport in mammals",
    "Gas exchange",
    "Infectious diseases",
    "Immunity",
    "Practical skills (AS)"
   ],
   "A": [
    "Energy and respiration",
    "Photosynthesis",
    "Homeostasis",
    "Control and coordination",
    "Inheritance",
    "Selection and evolution",
    "Classification, biodiversity and conservation",
    "Genetic technology",
    "Practical skills (A Level)"
   ]
  },
  "notes": "A new 2028-2030 syllabus is published but not used. June and November series (March for India). Practical skills also studied at both levels."
 },
 {
  "code": "9239",
  "title": "Cambridge International AS & A Level Global Perspectives & Research",
  "version": "2026-2028 syllabus, Version 3 (Dec 2025)",
  "versionKey": "2026-2028",
  "firstExam": 2026,
  "lastExam": 2028,
  "sourceKey": "cie-9239-syllabus-2026-2028",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/697359-2026-2028-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "c1",
    "number": "1",
    "name": "Written Exam",
    "type": "WRITTEN_PAPER",
    "minutes": 90,
    "marks": 45,
    "weightAS": 36,
    "weightA": 18,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "NOT_CONFIRMED (not stated; not relevant)",
    "resources": "Two source documents provided with the paper.",
    "questionTypes": "Three compulsory questions: Q1 structured short answers (5 marks), Q2 longer response on one source (15), Q3 essay on both sources (25). Skills-based; no prior topic knowledge required.",
    "notes": "Test date window per Cambridge timetable."
   },
   {
    "key": "c2",
    "number": "2",
    "name": "Essay",
    "type": "ESSAY",
    "minutes": null,
    "marks": 40,
    "weightAS": 32,
    "weightA": 16,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "N/A",
    "resources": "Candidate research; list of sources required.",
    "questionTypes": "Single-question essay title devised by candidate; continuous prose, 1750–2000 words (work beyond 2000 not marked).",
    "notes": "Externally marked coursework, submitted electronically."
   },
   {
    "key": "c3",
    "number": "3",
    "name": "Team Project",
    "type": "PRESENTATION",
    "minutes": null,
    "marks": 40,
    "weightAS": 32,
    "weightA": 16,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "N/A",
    "resources": "Audio/visual materials and verbatim transcript submitted with presentation.",
    "questionTypes": "Teams of 2–5 identify a local problem with global relevance. Individual presentation (30 marks, max 10 minutes, live recording or voiceover) + reflective paper (10 marks, max 800 words).",
    "notes": "Externally marked; team presentations not permitted for assessment. minutes=null because 10 min is a maximum running time, not an exam duration."
   },
   {
    "key": "c4",
    "number": "4",
    "name": "Cambridge Research Report",
    "type": "RESEARCH_REPORT",
    "minutes": null,
    "marks": 85,
    "weightAS": null,
    "weightA": 50,
    "levels": [
     "A"
    ],
    "calculator": "N/A",
    "resources": "Research proposal form (internally reviewed, not marked) submitted with work.",
    "questionTypes": "Research report up to 5000 words (75 marks) + research log (10 marks); single research question, non-specialist audience.",
    "notes": "A Level only; externally marked."
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; all AS components taken in the same exam series.",
    "componentSets": [
     [
      "c1",
      "c2",
      "c3"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "A Level staged over two years: AS components in Year 1 (AS result carried forward per Cambridge Handbook rules), remaining components in a later series.",
    "componentSets": [
     [
      "c1",
      "c2",
      "c3",
      "c4"
     ]
    ],
    "stages": [
     [
      [
       "c1",
       "c2",
       "c3"
      ],
      [
       "c4"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "A Level; all components taken in the same exam series.",
    "componentSets": [
     [
      "c1",
      "c2",
      "c3",
      "c4"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Research, analysis and evaluation",
    "weightAS": 65,
    "weightA": 65
   },
   {
    "key": "AO2",
    "name": "Reflection",
    "weightAS": 15,
    "weightA": 20
   },
   {
    "key": "AO3",
    "name": "Communication",
    "weightAS": 20,
    "weightA": 15
   }
  ],
  "topics": {
   "AS": [
    "Skills framework: the Critical Path (Deconstruction, Reconstruction, Reflection, Communication and collaboration)",
    "Global topics (study issues from at least three): Animal rights; Arts in an international context; Changing identities; Climate change; Crime; Cultural heritage; Demographic changes; Distribution of wealth; Economics of food; Endangered cultures; Energy; Environmental priorities; Ethical foreign policies; Ethics of food; Globalisation; Global inequality; Health issues; Human rights; Impact of technology; Industrial pollution; International aid; International law; Media and communication; Medical ethics and priorities; Migration and work; Political power and resistance; Quality of life; Scientific innovation; Social change and development; Social inequality; Sport in an international context; Sustainable futures; Tourism; Transport; Urbanisation"
   ],
   "A": [
    "Independent research: research methods and methodology; Cambridge Research Report on a candidate-chosen topic (no prescribed content)"
   ]
  },
  "notes": "AICE Diploma core subject (AS Level GP&R 9239 compulsory); also listed in AICE Group 4 (Interdisciplinary). Not available in March series. Global topic list from PDF two-column layout, re-sorted alphabetically."
 },
 {
  "code": "9093",
  "title": "Cambridge International AS & A Level English Language",
  "version": "2027-2028 syllabus, Version 1 (Sep 2024)",
  "versionKey": "2027-2028",
  "firstExam": 2027,
  "lastExam": 2028,
  "sourceKey": "cie-9093-syllabus-2027-2028",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/721359-2027-2028-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "p1",
    "number": "1",
    "name": "Reading",
    "type": "WRITTEN_PAPER",
    "minutes": 135,
    "marks": 50,
    "weightAS": 50,
    "weightA": 25,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "N/A",
    "resources": "Unseen texts in paper; dictionaries may not be used.",
    "questionTypes": "Two compulsory questions. Section A Directed response (25): 1(a) directed writing 150–200 words from a ~550–750-word text (10), 1(b) comparative analysis (15). Section B Text analysis (25) on a ~550–750-word text.",
    "notes": ""
   },
   {
    "key": "p2",
    "number": "2",
    "name": "Writing",
    "type": "WRITTEN_PAPER",
    "minutes": 120,
    "marks": 50,
    "weightAS": 50,
    "weightA": 25,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "N/A",
    "resources": "Dictionaries may not be used.",
    "questionTypes": "Section A (compulsory, 25): 1(a) short text ≤400 words (15), 1(b) reflective commentary (10). Section B (25): one of three extended writing questions (imaginative/descriptive, discursive/argumentative, review/critical), 600–900 words.",
    "notes": ""
   },
   {
    "key": "p3",
    "number": "3",
    "name": "Language Analysis",
    "type": "WRITTEN_PAPER",
    "minutes": 135,
    "marks": 50,
    "weightAS": null,
    "weightA": 25,
    "levels": [
     "A"
    ],
    "calculator": "N/A",
    "resources": "Prose text, n-gram graph and corpus word table (Section A); child language transcript (Section B). Dictionaries may not be used.",
    "questionTypes": "Two compulsory questions: Section A Language change (25); Section B Child language acquisition (25).",
    "notes": ""
   },
   {
    "key": "p4",
    "number": "4",
    "name": "Language Topics",
    "type": "WRITTEN_PAPER",
    "minutes": 135,
    "marks": 50,
    "weightAS": null,
    "weightA": 25,
    "levels": [
     "A"
    ],
    "calculator": "N/A",
    "resources": "~400–500-word stimulus text per section. Dictionaries may not be used.",
    "questionTypes": "Two compulsory essay questions: Section A English in the world (25); Section B Language and the self (25).",
    "notes": ""
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; all AS components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "A Level staged over two years: AS components in Year 1 (AS result carried forward per Cambridge Handbook rules), remaining components in a later series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4"
     ]
    ],
    "stages": [
     [
      [
       "p1",
       "p2"
      ],
      [
       "p3",
       "p4"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "A Level; all components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Read and demonstrate understanding of a wide variety of texts",
    "weightAS": 15,
    "weightA": 20
   },
   {
    "key": "AO2",
    "name": "Write effectively, creatively, accurately and appropriately, for a range of audiences and purposes",
    "weightAS": 45,
    "weightA": 30
   },
   {
    "key": "AO3",
    "name": "Analyse the ways in which writers' and speakers' choices of form, structure and language produce meaning and style",
    "weightAS": 40,
    "weightA": 20
   },
   {
    "key": "AO4",
    "name": "Demonstrate understanding of linguistic issues, concepts, methods and approaches",
    "weightAS": 0,
    "weightA": 20
   },
   {
    "key": "AO5",
    "name": "Analyse and synthesise language data from a variety of sources",
    "weightAS": 0,
    "weightA": 10
   }
  ],
  "topics": {
   "AS": [
    "Paper 1 – Reading (directed response; text analysis)",
    "Paper 2 – Writing (shorter writing and reflective commentary; extended writing)"
   ],
   "A": [
    "Paper 3 – Language Analysis: Language change; Child language acquisition",
    "Paper 4 – Language Topics: English in the world; Language and the self"
   ]
  },
  "notes": "Chosen as Group 2 candidate: cambridgeinternational.org AICE Diploma curriculum page lists English Language under Group 2: Languages, so no substitution with 9719 Spanish was needed. Staged route carries forward AS MARKS (syllabus wording 'carry forward their AS Level marks'), unlike other syllabi which say 'result'. Syllabus for 2024-2026 (635901) applies to 2026 exams; 2027 uses this new version."
 },
 {
  "code": "9708",
  "title": "Cambridge International AS & A Level Economics",
  "version": "2026-2028 syllabus, Version 2 (Dec 2025)",
  "versionKey": "2026-2028",
  "firstExam": 2026,
  "lastExam": 2028,
  "sourceKey": "cie-9708-syllabus-2026-2028",
  "sourceUrl": "https://www.cambridgeinternational.org/Images/697423-2026-2028-syllabus.pdf",
  "confidence": "HIGH",
  "components": [
   {
    "key": "p1",
    "number": "1",
    "name": "AS Level Multiple Choice",
    "type": "WRITTEN_PAPER",
    "minutes": 60,
    "marks": 30,
    "weightAS": 33,
    "weightA": 17,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Calculators may be used for all papers.",
    "resources": "Formulae are not given in the question papers.",
    "questionTypes": "30 multiple-choice questions; AS content; answers on answer sheet.",
    "notes": ""
   },
   {
    "key": "p2",
    "number": "2",
    "name": "AS Level Data Response and Essays",
    "type": "WRITTEN_PAPER",
    "minutes": 120,
    "marks": 60,
    "weightAS": 67,
    "weightA": 33,
    "levels": [
     "AS",
     "A"
    ],
    "calculator": "Calculators may be used.",
    "resources": "Formulae not given.",
    "questionTypes": "Section A: one data response (20); Section B: one of two two-part essays, mainly micro (20); Section C: one of two two-part essays, mainly macro (20).",
    "notes": ""
   },
   {
    "key": "p3",
    "number": "3",
    "name": "A Level Multiple Choice",
    "type": "WRITTEN_PAPER",
    "minutes": 75,
    "marks": 30,
    "weightAS": null,
    "weightA": 17,
    "levels": [
     "A"
    ],
    "calculator": "Calculators may be used.",
    "resources": "Formulae not given.",
    "questionTypes": "30 multiple-choice questions; A Level content, AS knowledge assumed.",
    "notes": ""
   },
   {
    "key": "p4",
    "number": "4",
    "name": "A Level Data Response and Essays",
    "type": "WRITTEN_PAPER",
    "minutes": 120,
    "marks": 60,
    "weightAS": null,
    "weightA": 33,
    "levels": [
     "A"
    ],
    "calculator": "Calculators may be used.",
    "resources": "Formulae not given.",
    "questionTypes": "Section A: one data response (20); Section B: one of two unstructured micro essays (20); Section C: one of two unstructured macro essays (20).",
    "notes": ""
   }
  ],
  "routes": [
   {
    "key": "AS_ONLY",
    "description": "AS Level only; all AS components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2"
     ]
    ],
    "stages": null
   },
   {
    "key": "A_LEVEL_STAGED",
    "description": "A Level staged over two years: AS components in Year 1 (AS result carried forward per Cambridge Handbook rules), remaining components in a later series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4"
     ]
    ],
    "stages": [
     [
      [
       "p1",
       "p2"
      ],
      [
       "p3",
       "p4"
      ]
     ]
    ]
   },
   {
    "key": "A_LEVEL_LINEAR",
    "description": "A Level; all components taken in the same exam series.",
    "componentSets": [
     [
      "p1",
      "p2",
      "p3",
      "p4"
     ]
    ],
    "stages": null
   }
  ],
  "assessmentObjectives": [
   {
    "key": "AO1",
    "name": "Knowledge and understanding",
    "weightAS": 35,
    "weightA": 35
   },
   {
    "key": "AO2",
    "name": "Analysis",
    "weightAS": 40,
    "weightA": 40
   },
   {
    "key": "AO3",
    "name": "Evaluation",
    "weightAS": 25,
    "weightA": 25
   }
  ],
  "topics": {
   "AS": [
    "1 Basic economic ideas and resource allocation",
    "2 The price system and the microeconomy",
    "3 Government microeconomic intervention",
    "4 The macroeconomy",
    "5 Government macroeconomic intervention",
    "6 International economic issues"
   ],
   "A": [
    "7 The price system and the microeconomy",
    "8 Government microeconomic intervention",
    "9 The macroeconomy",
    "10 Government macroeconomic intervention",
    "11 International economic issues"
   ]
  },
  "notes": "Economics is listed under AICE Group 3: Arts and Humanities on the cambridgeinternational.org AICE Diploma curriculum page, so History 9489 substitution not needed. AS topics 1.1–6.5; A Level topics 1.1–11.6. Note the official AS-paper weights are 33/67 at AS and 17/33 at A Level (sum 100)."
 }
];

export const AICE_SOURCES: AssessmentSourceSeed[] = [
 {
  "key": "cie-9709-syllabus-2026-2027",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level Mathematics 9709 – Use this syllabus for exams in 2026 and 2027 (Version 4)",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf",
  "documentVersion": "2026-2027 syllabus, Version 4 (Dec 2025)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2026-2027",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-9702-syllabus-2025-2027",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level Physics 9702 – Use this syllabus for exams in 2025, 2026 and 2027 (Version 1)",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/664565-2025-2027-syllabus.pdf",
  "documentVersion": "2025-2027 syllabus (covers examination in 2027)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2025-2027",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-9701-syllabus-2025-2027",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level Chemistry 9701 – Use this syllabus for exams in 2025, 2026 and 2027",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/664563-2025-2027-syllabus.pdf",
  "documentVersion": "2025-2027 syllabus (covers examination in 2027)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2025-2027",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-9700-syllabus-2025-2027",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level Biology 9700 – Use this syllabus for exams in 2025, 2026 and 2027",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/664560-2025-2027-syllabus.pdf",
  "documentVersion": "2025-2027 syllabus (covers examination in 2027)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2025-2027",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-9239-syllabus-2026-2028",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level Global Perspectives & Research 9239 – Use this syllabus for exams in 2026, 2027 and 2028 (Version 3)",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/697359-2026-2028-syllabus.pdf",
  "documentVersion": "2026-2028 syllabus, Version 3 (Dec 2025)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2026-2028",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-9093-syllabus-2027-2028",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level English Language 9093 – Use this syllabus for exams in 2027 and 2028 (Version 1)",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/721359-2027-2028-syllabus.pdf",
  "documentVersion": "2027-2028 syllabus, Version 1 (Sep 2024)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2027-2028",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-9708-syllabus-2026-2028",
  "framework": "CAMBRIDGE",
  "title": "Syllabus Cambridge International AS & A Level Economics 9708 – Use this syllabus for exams in 2026, 2027 and 2028 (Version 2)",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/697423-2026-2028-syllabus.pdf",
  "documentVersion": "2026-2028 syllabus, Version 2 (Dec 2025)",
  "publicationYear": null,
  "effectiveSession": "Examination in 2026-2028",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-aice-qualification",
  "framework": "CAMBRIDGE",
  "title": "Cambridge AICE Diploma qualification",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-aice-diploma/qualification/",
  "publicationYear": null,
  "effectiveSession": "Current web page as retrieved 2026-10-01; no effective series stated (25-month example cites Nov 201",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-aice-curriculum",
  "framework": "CAMBRIDGE",
  "title": "Cambridge AICE Diploma curriculum",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-aice-diploma/curriculum/",
  "publicationYear": null,
  "effectiveSession": "Current web page as retrieved 2026-10-01; no version/year stated; page says 'not a definitive list' ",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-aice-overview",
  "framework": "CAMBRIDGE",
  "title": "Cambridge AICE Diploma",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-aice-diploma/",
  "publicationYear": null,
  "effectiveSession": "Current web page as retrieved 2026-10-01",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-us-grades-guide",
  "framework": "CAMBRIDGE",
  "title": "Guide to Cambridge grades for US high schools",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/usa/about-cambridge-international-us/guide-to-cambridge-grades/",
  "publicationYear": null,
  "effectiveSession": "Current web page as retrieved 2026-10-01",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-grading-scale-pdf",
  "framework": "CAMBRIDGE",
  "title": "Cambridge International AS & A Level Grading Scale",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/Images/635652-cambridge-advanced-grading-scale.pdf",
  "publicationYear": null,
  "effectiveSession": "Undated PDF; retrieved 2026-10-01",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-gt-index",
  "framework": "CAMBRIDGE",
  "title": "Grade threshold tables (Cambridge International AS & A Level)",
  "publisher": "Cambridge International",
  "url": "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-international-as-and-a-levels/grade-threshold-tables/",
  "publicationYear": null,
  "effectiveSession": "Series March 2022 through June 2026 listed as of 2026-10-01",
  "confidence": "HIGH",
  "license": "PUBLIC"
 },
 {
  "key": "cie-help-aice-search-snippets",
  "framework": "CAMBRIDGE",
  "title": "AICE Diploma: Credits - FAQs (help centre; blocked by bot check, seen only via search snippets)",
  "publisher": "Cambridge International",
  "url": "https://help.cambridgeinternational.org/hc/en-gb/articles/203543872-AICE-Diploma-Credits-FAQs",
  "publicationYear": null,
  "effectiveSession": "Unknown",
  "confidence": "LOW",
  "license": "PUBLIC"
 }
];
